export interface DailyVerse {
  en: { text: string; ref: string };
  es: { text: string; ref: string };
}

/**
 * 365 curated short verses — one per day-of-year (index 0 = Jan 1).
 * Each entry has English + Spanish. Kept short (1–2 lines) for widget display.
 */
export const DAILY_VERSES: DailyVerse[] = [
  // ── January ──
  { en: { text: "In the beginning God created the heavens and the earth.", ref: "Genesis 1:1" }, es: { text: "En el principio Dios creó los cielos y la tierra.", ref: "Génesis 1:1" } },
  { en: { text: "The Lord is my shepherd; I shall not want.", ref: "Psalm 23:1" }, es: { text: "El Señor es mi pastor; nada me faltará.", ref: "Salmo 23:1" } },
  { en: { text: "Trust in the Lord with all your heart.", ref: "Proverbs 3:5" }, es: { text: "Confía en el Señor con todo tu corazón.", ref: "Proverbios 3:5" } },
  { en: { text: "For God so loved the world that He gave His only Son.", ref: "John 3:16" }, es: { text: "Porque de tal manera amó Dios al mundo que dio a Su Hijo unigénito.", ref: "Juan 3:16" } },
  { en: { text: "I can do all things through Christ who strengthens me.", ref: "Philippians 4:13" }, es: { text: "Todo lo puedo en Cristo que me fortalece.", ref: "Filipenses 4:13" } },
  { en: { text: "The Lord is my light and my salvation — whom shall I fear?", ref: "Psalm 27:1" }, es: { text: "El Señor es mi luz y mi salvación, ¿a quién temeré?", ref: "Salmo 27:1" } },
  { en: { text: "Be strong and courageous. Do not be afraid.", ref: "Joshua 1:9" }, es: { text: "Sé fuerte y valiente. No tengas miedo.", ref: "Josué 1:9" } },
  { en: { text: "Cast all your anxiety on Him because He cares for you.", ref: "1 Peter 5:7" }, es: { text: "Echa toda tu ansiedad sobre Él, porque Él cuida de ti.", ref: "1 Pedro 5:7" } },
  { en: { text: "The joy of the Lord is your strength.", ref: "Nehemiah 8:10" }, es: { text: "El gozo del Señor es tu fortaleza.", ref: "Nehemías 8:10" } },
  { en: { text: "Be still, and know that I am God.", ref: "Psalm 46:10" }, es: { text: "Estad quietos, y conoced que yo soy Dios.", ref: "Salmo 46:10" } },
  { en: { text: "He gives strength to the weary and increases the power of the weak.", ref: "Isaiah 40:29" }, es: { text: "Él da fuerzas al cansado y aumenta el poder del débil.", ref: "Isaías 40:29" } },
  { en: { text: "God is our refuge and strength, an ever-present help in trouble.", ref: "Psalm 46:1" }, es: { text: "Dios es nuestro refugio y fortaleza, socorro en las tribulaciones.", ref: "Salmo 46:1" } },
  { en: { text: "Come to me, all you who are weary, and I will give you rest.", ref: "Matthew 11:28" }, es: { text: "Venid a mí todos los que estáis cansados, y yo os haré descansar.", ref: "Mateo 11:28" } },
  { en: { text: "The Lord your God is with you, the Mighty Warrior who saves.", ref: "Zephaniah 3:17" }, es: { text: "El Señor tu Dios está en medio de ti, guerrero poderoso que salva.", ref: "Sofonías 3:17" } },
  { en: { text: "Do not be anxious about anything, but in everything, by prayer.", ref: "Philippians 4:6" }, es: { text: "No se preocupen por nada; en todo, mediante oración.", ref: "Filipenses 4:6" } },
  { en: { text: "For I know the plans I have for you, declares the Lord.", ref: "Jeremiah 29:11" }, es: { text: "Porque yo sé los planes que tengo para ti, dice el Señor.", ref: "Jeremías 29:11" } },
  { en: { text: "The name of the Lord is a fortified tower; the righteous run to it.", ref: "Proverbs 18:10" }, es: { text: "El nombre del Señor es torre fuerte; a ella corre el justo.", ref: "Proverbios 18:10" } },
  { en: { text: "Wait for the Lord; be strong and take heart.", ref: "Psalm 27:14" }, es: { text: "Espera en el Señor; sé fuerte y valiente.", ref: "Salmo 27:14" } },
  { en: { text: "And we know that in all things God works for the good.", ref: "Romans 8:28" }, es: { text: "Sabemos que Dios obra en todas las cosas para bien.", ref: "Romanos 8:28" } },
  { en: { text: "His mercies are new every morning; great is Your faithfulness.", ref: "Lamentations 3:23" }, es: { text: "Sus misericordias son nuevas cada mañana; grande es Tu fidelidad.", ref: "Lamentaciones 3:23" } },
  { en: { text: "The Lord is close to the brokenhearted.", ref: "Psalm 34:18" }, es: { text: "El Señor está cerca de los quebrantados de corazón.", ref: "Salmo 34:18" } },
  { en: { text: "Delight yourself in the Lord, and He will give you your desires.", ref: "Psalm 37:4" }, es: { text: "Deléitate en el Señor, y Él te concederá los deseos de tu corazón.", ref: "Salmo 37:4" } },
  { en: { text: "But the fruit of the Spirit is love, joy, peace, patience.", ref: "Galatians 5:22" }, es: { text: "Pero el fruto del Espíritu es amor, gozo, paz, paciencia.", ref: "Gálatas 5:22" } },
  { en: { text: "Have I not commanded you? Be strong and courageous.", ref: "Joshua 1:9" }, es: { text: "¿No te lo he ordenado? Sé fuerte y valiente.", ref: "Josué 1:9" } },
  { en: { text: "My grace is sufficient for you, for my power is made perfect in weakness.", ref: "2 Corinthians 12:9" }, es: { text: "Mi gracia te basta, porque mi poder se perfecciona en la debilidad.", ref: "2 Corintios 12:9" } },
  { en: { text: "The Lord is faithful, and He will strengthen you.", ref: "2 Thessalonians 3:3" }, es: { text: "Fiel es el Señor, que os fortalecerá.", ref: "2 Tesalonicenses 3:3" } },
  { en: { text: "He who began a good work in you will carry it to completion.", ref: "Philippians 1:6" }, es: { text: "El que comenzó la buena obra en ti la perfeccionará.", ref: "Filipenses 1:6" } },
  { en: { text: "Your word is a lamp for my feet, a light on my path.", ref: "Psalm 119:105" }, es: { text: "Tu palabra es lámpara a mis pies y luz en mi camino.", ref: "Salmo 119:105" } },
  { en: { text: "Love is patient, love is kind. It does not envy.", ref: "1 Corinthians 13:4" }, es: { text: "El amor es paciente, es bondadoso. No tiene envidia.", ref: "1 Corintios 13:4" } },
  { en: { text: "The earth is the Lord's, and everything in it.", ref: "Psalm 24:1" }, es: { text: "Del Señor es la tierra y todo lo que hay en ella.", ref: "Salmo 24:1" } },
  { en: { text: "Create in me a pure heart, O God.", ref: "Psalm 51:10" }, es: { text: "Crea en mí un corazón limpio, oh Dios.", ref: "Salmo 51:10" } },
  // ── February ──
  { en: { text: "Above all, love each other deeply.", ref: "1 Peter 4:8" }, es: { text: "Ante todo, ámense los unos a los otros profundamente.", ref: "1 Pedro 4:8" } },
  { en: { text: "A friend loves at all times.", ref: "Proverbs 17:17" }, es: { text: "En todo tiempo ama el amigo.", ref: "Proverbios 17:17" } },
  { en: { text: "Let all that you do be done in love.", ref: "1 Corinthians 16:14" }, es: { text: "Que todo lo que hagan, lo hagan con amor.", ref: "1 Corintios 16:14" } },
  { en: { text: "Beloved, let us love one another, for love comes from God.", ref: "1 John 4:7" }, es: { text: "Amados, amémonos unos a otros, porque el amor viene de Dios.", ref: "1 Juan 4:7" } },
  { en: { text: "Love the Lord your God with all your heart.", ref: "Deuteronomy 6:5" }, es: { text: "Ama al Señor tu Dios con todo tu corazón.", ref: "Deuteronomio 6:5" } },
  { en: { text: "Love your neighbor as yourself.", ref: "Mark 12:31" }, es: { text: "Ama a tu prójimo como a ti mismo.", ref: "Marcos 12:31" } },
  { en: { text: "Greater love has no one than this: to lay down one's life.", ref: "John 15:13" }, es: { text: "Nadie tiene mayor amor que este: dar la vida por sus amigos.", ref: "Juan 15:13" } },
  { en: { text: "God demonstrates His own love for us in this.", ref: "Romans 5:8" }, es: { text: "Dios demuestra Su amor por nosotros en esto.", ref: "Romanos 5:8" } },
  { en: { text: "Nothing can separate us from the love of God.", ref: "Romans 8:39" }, es: { text: "Nada nos podrá separar del amor de Dios.", ref: "Romanos 8:39" } },
  { en: { text: "We love because He first loved us.", ref: "1 John 4:19" }, es: { text: "Nosotros amamos porque Él nos amó primero.", ref: "1 Juan 4:19" } },
  { en: { text: "How good and pleasant it is when God's people live in unity!", ref: "Psalm 133:1" }, es: { text: "¡Cuán bueno y cuán agradable es que los hermanos vivan en armonía!", ref: "Salmo 133:1" } },
  { en: { text: "Bear with each other and forgive one another.", ref: "Colossians 3:13" }, es: { text: "Sopórtense unos a otros y perdónense mutuamente.", ref: "Colosenses 3:13" } },
  { en: { text: "Be kind and compassionate to one another.", ref: "Ephesians 4:32" }, es: { text: "Sean bondadosos y compasivos unos con otros.", ref: "Efesios 4:32" } },
  { en: { text: "Whoever pursues righteousness and love finds life.", ref: "Proverbs 21:21" }, es: { text: "El que sigue la justicia y el amor halla la vida.", ref: "Proverbios 21:21" } },
  { en: { text: "See what great love the Father has lavished on us.", ref: "1 John 3:1" }, es: { text: "Miren cuán gran amor nos ha dado el Padre.", ref: "1 Juan 3:1" } },
  { en: { text: "The Lord is gracious and compassionate, slow to anger.", ref: "Psalm 145:8" }, es: { text: "El Señor es clemente y compasivo, lento para la ira.", ref: "Salmo 145:8" } },
  { en: { text: "I have loved you with an everlasting love.", ref: "Jeremiah 31:3" }, es: { text: "Con amor eterno te he amado.", ref: "Jeremías 31:3" } },
  { en: { text: "Place me like a seal over your heart.", ref: "Song of Solomon 8:6" }, es: { text: "Ponme como un sello sobre tu corazón.", ref: "Cantar de los Cantares 8:6" } },
  { en: { text: "Many waters cannot quench love.", ref: "Song of Solomon 8:7" }, es: { text: "Las muchas aguas no pueden apagar el amor.", ref: "Cantar de los Cantares 8:7" } },
  { en: { text: "And now these three remain: faith, hope and love.", ref: "1 Corinthians 13:13" }, es: { text: "Ahora permanecen la fe, la esperanza y el amor.", ref: "1 Corintios 13:13" } },
  { en: { text: "Love never fails.", ref: "1 Corinthians 13:8" }, es: { text: "El amor nunca deja de ser.", ref: "1 Corintios 13:8" } },
  { en: { text: "Walk in the way of love, just as Christ loved us.", ref: "Ephesians 5:2" }, es: { text: "Vivan en amor, así como Cristo nos amó.", ref: "Efesios 5:2" } },
  { en: { text: "Give thanks to the Lord, for He is good; His love endures forever.", ref: "Psalm 107:1" }, es: { text: "Den gracias al Señor, porque es bueno; Su amor perdura para siempre.", ref: "Salmo 107:1" } },
  { en: { text: "Love does no harm to a neighbor.", ref: "Romans 13:10" }, es: { text: "El amor no hace mal al prójimo.", ref: "Romanos 13:10" } },
  { en: { text: "Let the morning bring me word of Your unfailing love.", ref: "Psalm 143:8" }, es: { text: "Hazme oír por la mañana Tu misericordia.", ref: "Salmo 143:8" } },
  { en: { text: "The Lord your God is in your midst; He will rejoice over you.", ref: "Zephaniah 3:17" }, es: { text: "El Señor tu Dios está en medio de ti; se gozará sobre ti.", ref: "Sofonías 3:17" } },
  { en: { text: "Husbands, love your wives, just as Christ loved the church.", ref: "Ephesians 5:25" }, es: { text: "Esposos, amen a sus esposas, así como Cristo amó a la iglesia.", ref: "Efesios 5:25" } },
  { en: { text: "Do everything in love.", ref: "1 Corinthians 16:14" }, es: { text: "Hagan todo con amor.", ref: "1 Corintios 16:14" } },
  // ── March ──
  { en: { text: "The Lord is my rock, my fortress and my deliverer.", ref: "Psalm 18:2" }, es: { text: "El Señor es mi roca, mi fortaleza y mi libertador.", ref: "Salmo 18:2" } },
  { en: { text: "He will cover you with His feathers, and under His wings you will find refuge.", ref: "Psalm 91:4" }, es: { text: "Con Sus plumas te cubrirá, y bajo Sus alas hallarás refugio.", ref: "Salmo 91:4" } },
  { en: { text: "When I am afraid, I put my trust in You.", ref: "Psalm 56:3" }, es: { text: "Cuando tengo miedo, pongo mi confianza en Ti.", ref: "Salmo 56:3" } },
  { en: { text: "The righteous cry out, and the Lord hears them.", ref: "Psalm 34:17" }, es: { text: "Los justos claman, y el Señor los oye.", ref: "Salmo 34:17" } },
  { en: { text: "Seek the Lord while He may be found.", ref: "Isaiah 55:6" }, es: { text: "Busquen al Señor mientras pueda ser hallado.", ref: "Isaías 55:6" } },
  { en: { text: "Draw near to God and He will draw near to you.", ref: "James 4:8" }, es: { text: "Acérquense a Dios, y Él se acercará a ustedes.", ref: "Santiago 4:8" } },
  { en: { text: "Those who hope in the Lord will renew their strength.", ref: "Isaiah 40:31" }, es: { text: "Los que esperan en el Señor renovarán sus fuerzas.", ref: "Isaías 40:31" } },
  { en: { text: "The Lord makes firm the steps of the one who delights in Him.", ref: "Psalm 37:23" }, es: { text: "El Señor afirma los pasos del que se deleita en Él.", ref: "Salmo 37:23" } },
  { en: { text: "In quietness and trust is your strength.", ref: "Isaiah 30:15" }, es: { text: "En la quietud y la confianza está su fortaleza.", ref: "Isaías 30:15" } },
  { en: { text: "I will never leave you nor forsake you.", ref: "Hebrews 13:5" }, es: { text: "Nunca te dejaré ni te abandonaré.", ref: "Hebreos 13:5" } },
  { en: { text: "The Lord will fight for you; you need only to be still.", ref: "Exodus 14:14" }, es: { text: "El Señor peleará por ustedes; solo quédense quietos.", ref: "Éxodo 14:14" } },
  { en: { text: "As for God, His way is perfect.", ref: "Psalm 18:30" }, es: { text: "En cuanto a Dios, Su camino es perfecto.", ref: "Salmo 18:30" } },
  { en: { text: "The Lord watches over the way of the righteous.", ref: "Psalm 1:6" }, es: { text: "El Señor cuida el camino de los justos.", ref: "Salmo 1:6" } },
  { en: { text: "Every good and perfect gift is from above.", ref: "James 1:17" }, es: { text: "Toda buena dádiva y todo don perfecto viene de lo alto.", ref: "Santiago 1:17" } },
  { en: { text: "Humble yourselves before the Lord, and He will lift you up.", ref: "James 4:10" }, es: { text: "Humíllense delante del Señor, y Él los exaltará.", ref: "Santiago 4:10" } },
  { en: { text: "Commit to the Lord whatever you do, and He will establish your plans.", ref: "Proverbs 16:3" }, es: { text: "Encomienda al Señor todo lo que haces, y Él establecerá tus planes.", ref: "Proverbios 16:3" } },
  { en: { text: "Let the peace of Christ rule in your hearts.", ref: "Colossians 3:15" }, es: { text: "Que la paz de Cristo gobierne en sus corazones.", ref: "Colosenses 3:15" } },
  { en: { text: "The Lord is near to all who call on Him in truth.", ref: "Psalm 145:18" }, es: { text: "El Señor está cerca de todos los que lo invocan de verdad.", ref: "Salmo 145:18" } },
  { en: { text: "Set your minds on things above, not on earthly things.", ref: "Colossians 3:2" }, es: { text: "Pongan la mira en las cosas de arriba, no en las de la tierra.", ref: "Colosenses 3:2" } },
  { en: { text: "If God is for us, who can be against us?", ref: "Romans 8:31" }, es: { text: "Si Dios está por nosotros, ¿quién contra nosotros?", ref: "Romanos 8:31" } },
  { en: { text: "For where two or three gather in My name, there am I.", ref: "Matthew 18:20" }, es: { text: "Donde dos o tres se reúnen en Mi nombre, allí estoy Yo.", ref: "Mateo 18:20" } },
  { en: { text: "He has made everything beautiful in its time.", ref: "Ecclesiastes 3:11" }, es: { text: "Todo lo hizo hermoso en su tiempo.", ref: "Eclesiastés 3:11" } },
  { en: { text: "Taste and see that the Lord is good.", ref: "Psalm 34:8" }, es: { text: "Gusten y vean que el Señor es bueno.", ref: "Salmo 34:8" } },
  { en: { text: "This is the day the Lord has made; let us rejoice.", ref: "Psalm 118:24" }, es: { text: "Este es el día que el Señor ha hecho; alegrémonos.", ref: "Salmo 118:24" } },
  { en: { text: "The Lord gives wisdom; from His mouth come knowledge.", ref: "Proverbs 2:6" }, es: { text: "El Señor da sabiduría; de Su boca vienen el conocimiento.", ref: "Proverbios 2:6" } },
  { en: { text: "For nothing will be impossible with God.", ref: "Luke 1:37" }, es: { text: "Porque nada será imposible para Dios.", ref: "Lucas 1:37" } },
  { en: { text: "Whoever walks in integrity walks securely.", ref: "Proverbs 10:9" }, es: { text: "Quien camina con integridad camina seguro.", ref: "Proverbios 10:9" } },
  { en: { text: "But seek first His kingdom and His righteousness.", ref: "Matthew 6:33" }, es: { text: "Busquen primero Su reino y Su justicia.", ref: "Mateo 6:33" } },
  { en: { text: "You will keep in perfect peace those whose minds are steadfast.", ref: "Isaiah 26:3" }, es: { text: "Tú guardarás en perfecta paz al de mente firme.", ref: "Isaías 26:3" } },
  { en: { text: "I am the way, the truth, and the life.", ref: "John 14:6" }, es: { text: "Yo soy el camino, la verdad y la vida.", ref: "Juan 14:6" } },
  { en: { text: "He is risen! He is not here.", ref: "Mark 16:6" }, es: { text: "¡Ha resucitado! No está aquí.", ref: "Marcos 16:6" } },
  // ── April ──
  { en: { text: "I am the resurrection and the life.", ref: "John 11:25" }, es: { text: "Yo soy la resurrección y la vida.", ref: "Juan 11:25" } },
  { en: { text: "Death has been swallowed up in victory.", ref: "1 Corinthians 15:54" }, es: { text: "La muerte ha sido satisfecha por la victoria.", ref: "1 Corintios 15:54" } },
  { en: { text: "Because I live, you also will live.", ref: "John 14:19" }, es: { text: "Porque yo vivo, ustedes también vivirán.", ref: "Juan 14:19" } },
  { en: { text: "In my Father's house are many rooms.", ref: "John 14:2" }, es: { text: "En la casa de Mi Padre hay muchas moradas.", ref: "Juan 14:2" } },
  { en: { text: "He was pierced for our transgressions.", ref: "Isaiah 53:5" }, es: { text: "Fue traspasado por nuestras transgresiones.", ref: "Isaías 53:5" } },
  { en: { text: "It is finished.", ref: "John 19:30" }, es: { text: "Consumado es.", ref: "Juan 19:30" } },
  { en: { text: "You will seek Me and find Me when you search with all your heart.", ref: "Jeremiah 29:13" }, es: { text: "Me buscarán y me encontrarán cuando me busquen de todo corazón.", ref: "Jeremías 29:13" } },
  { en: { text: "I am the vine; you are the branches.", ref: "John 15:5" }, es: { text: "Yo soy la vid; ustedes son las ramas.", ref: "Juan 15:5" } },
  { en: { text: "The Lord is good to all; He has compassion on all He has made.", ref: "Psalm 145:9" }, es: { text: "El Señor es bueno con todos; tiene compasión de toda Su creación.", ref: "Salmo 145:9" } },
  { en: { text: "Ask and it will be given to you; seek and you will find.", ref: "Matthew 7:7" }, es: { text: "Pidan, y se les dará; busquen, y encontrarán.", ref: "Mateo 7:7" } },
  { en: { text: "Let us not grow weary of doing good.", ref: "Galatians 6:9" }, es: { text: "No nos cansemos de hacer el bien.", ref: "Gálatas 6:9" } },
  { en: { text: "You are the salt of the earth.", ref: "Matthew 5:13" }, es: { text: "Ustedes son la sal de la tierra.", ref: "Mateo 5:13" } },
  { en: { text: "The steadfast love of the Lord never ceases.", ref: "Lamentations 3:22" }, es: { text: "El amor del Señor nunca cesa.", ref: "Lamentaciones 3:22" } },
  { en: { text: "I will praise You, Lord, with all my heart.", ref: "Psalm 9:1" }, es: { text: "Te alabaré, Señor, con todo mi corazón.", ref: "Salmo 9:1" } },
  { en: { text: "He heals the brokenhearted and binds up their wounds.", ref: "Psalm 147:3" }, es: { text: "Él sana a los quebrantados de corazón y venda sus heridas.", ref: "Salmo 147:3" } },
  { en: { text: "Be transformed by the renewing of your mind.", ref: "Romans 12:2" }, es: { text: "Sean transformados mediante la renovación de su mente.", ref: "Romanos 12:2" } },
  { en: { text: "The Lord bless you and keep you.", ref: "Numbers 6:24" }, es: { text: "El Señor te bendiga y te guarde.", ref: "Números 6:24" } },
  { en: { text: "The Lord make His face shine on you.", ref: "Numbers 6:25" }, es: { text: "El Señor haga resplandecer Su rostro sobre ti.", ref: "Números 6:25" } },
  { en: { text: "The Lord turn His face toward you and give you peace.", ref: "Numbers 6:26" }, es: { text: "El Señor vuelva Su rostro hacia ti y te dé paz.", ref: "Números 6:26" } },
  { en: { text: "Let us run with perseverance the race marked out for us.", ref: "Hebrews 12:1" }, es: { text: "Corramos con perseverancia la carrera que tenemos por delante.", ref: "Hebreos 12:1" } },
  { en: { text: "With God all things are possible.", ref: "Matthew 19:26" }, es: { text: "Para Dios todo es posible.", ref: "Mateo 19:26" } },
  { en: { text: "I praise You because I am fearfully and wonderfully made.", ref: "Psalm 139:14" }, es: { text: "Te alabo porque fui hecho de manera formidable y maravillosa.", ref: "Salmo 139:14" } },
  { en: { text: "How priceless is Your unfailing love, O God!", ref: "Psalm 36:7" }, es: { text: "¡Cuán precioso es Tu amor inagotable, oh Dios!", ref: "Salmo 36:7" } },
  { en: { text: "The heavens declare the glory of God.", ref: "Psalm 19:1" }, es: { text: "Los cielos cuentan la gloria de Dios.", ref: "Salmo 19:1" } },
  { en: { text: "Be joyful in hope, patient in affliction, faithful in prayer.", ref: "Romans 12:12" }, es: { text: "Gozosos en la esperanza, pacientes en la tribulación, fieles en la oración.", ref: "Romanos 12:12" } },
  { en: { text: "Who is like You, Lord — majestic in holiness?", ref: "Exodus 15:11" }, es: { text: "¿Quién como Tú, Señor — majestuoso en santidad?", ref: "Éxodo 15:11" } },
  { en: { text: "Great is the Lord and most worthy of praise.", ref: "Psalm 145:3" }, es: { text: "Grande es el Señor y muy digno de alabanza.", ref: "Salmo 145:3" } },
  { en: { text: "Let everything that has breath praise the Lord.", ref: "Psalm 150:6" }, es: { text: "¡Que todo lo que respira alabe al Señor!", ref: "Salmo 150:6" } },
  { en: { text: "Blessed are the pure in heart, for they will see God.", ref: "Matthew 5:8" }, es: { text: "Bienaventurados los de limpio corazón, porque verán a Dios.", ref: "Mateo 5:8" } },
  { en: { text: "The grass withers, but the word of our God endures forever.", ref: "Isaiah 40:8" }, es: { text: "La hierba se seca, pero la palabra de nuestro Dios permanece para siempre.", ref: "Isaías 40:8" } },
  // ── May ──
  { en: { text: "Her children arise and call her blessed.", ref: "Proverbs 31:28" }, es: { text: "Sus hijos se levantan y la llaman bienaventurada.", ref: "Proverbios 31:28" } },
  { en: { text: "Charm is deceptive, and beauty is fleeting.", ref: "Proverbs 31:30" }, es: { text: "Engañosa es la gracia y vana la hermosura.", ref: "Proverbios 31:30" } },
  { en: { text: "She is clothed with strength and dignity.", ref: "Proverbs 31:25" }, es: { text: "Fuerza y dignidad son su vestidura.", ref: "Proverbios 31:25" } },
  { en: { text: "Children are a heritage from the Lord.", ref: "Psalm 127:3" }, es: { text: "Los hijos son una herencia del Señor.", ref: "Salmo 127:3" } },
  { en: { text: "Train up a child in the way he should go.", ref: "Proverbs 22:6" }, es: { text: "Instruye al niño en su camino.", ref: "Proverbios 22:6" } },
  { en: { text: "Honor your father and your mother.", ref: "Exodus 20:12" }, es: { text: "Honra a tu padre y a tu madre.", ref: "Éxodo 20:12" } },
  { en: { text: "The Lord is my strength and my song.", ref: "Exodus 15:2" }, es: { text: "El Señor es mi fuerza y mi cántico.", ref: "Éxodo 15:2" } },
  { en: { text: "Teach me Your way, Lord; lead me in a straight path.", ref: "Psalm 27:11" }, es: { text: "Enséñame Tu camino, Señor; guíame por senda recta.", ref: "Salmo 27:11" } },
  { en: { text: "Show me Your ways, Lord, teach me Your paths.", ref: "Psalm 25:4" }, es: { text: "Muéstrame Tus caminos, Señor; enséñame Tus sendas.", ref: "Salmo 25:4" } },
  { en: { text: "Direct my footsteps according to Your word.", ref: "Psalm 119:133" }, es: { text: "Dirige mis pasos conforme a Tu palabra.", ref: "Salmo 119:133" } },
  { en: { text: "Guide me in Your truth and teach me.", ref: "Psalm 25:5" }, es: { text: "Guíame en Tu verdad y enséñame.", ref: "Salmo 25:5" } },
  { en: { text: "I will instruct you and teach you in the way you should go.", ref: "Psalm 32:8" }, es: { text: "Te instruiré y te enseñaré el camino que debes seguir.", ref: "Salmo 32:8" } },
  { en: { text: "The Lord will guide you always.", ref: "Isaiah 58:11" }, es: { text: "El Señor te guiará siempre.", ref: "Isaías 58:11" } },
  { en: { text: "He leads me beside quiet waters, He refreshes my soul.", ref: "Psalm 23:2-3" }, es: { text: "Me conduce junto a aguas tranquilas, restaura mi alma.", ref: "Salmo 23:2-3" } },
  { en: { text: "Your ears will hear a voice behind you, saying, 'This is the way.'", ref: "Isaiah 30:21" }, es: { text: "Tus oídos oirán una voz detrás de ti que dice: 'Este es el camino.'", ref: "Isaías 30:21" } },
  { en: { text: "Lead me, Lord, in Your righteousness.", ref: "Psalm 5:8" }, es: { text: "Guíame, Señor, en Tu justicia.", ref: "Salmo 5:8" } },
  { en: { text: "Send out Your light and Your truth; let them lead me.", ref: "Psalm 43:3" }, es: { text: "Envía Tu luz y Tu verdad; que ellas me guíen.", ref: "Salmo 43:3" } },
  { en: { text: "The steps of a good man are ordered by the Lord.", ref: "Psalm 37:23" }, es: { text: "Los pasos del hombre bueno son ordenados por el Señor.", ref: "Salmo 37:23" } },
  { en: { text: "He makes me lie down in green pastures.", ref: "Psalm 23:2" }, es: { text: "En verdes pastos me hace descansar.", ref: "Salmo 23:2" } },
  { en: { text: "Teach me to do Your will, for You are my God.", ref: "Psalm 143:10" }, es: { text: "Enséñame a hacer Tu voluntad, porque Tú eres mi Dios.", ref: "Salmo 143:10" } },
  { en: { text: "Open my eyes that I may see wonderful things in Your law.", ref: "Psalm 119:18" }, es: { text: "Abre mis ojos para que vea las maravillas de Tu ley.", ref: "Salmo 119:18" } },
  { en: { text: "O Lord, You are my God; I will exalt You and praise Your name.", ref: "Isaiah 25:1" }, es: { text: "Oh Señor, Tú eres mi Dios; te exaltaré y alabaré Tu nombre.", ref: "Isaías 25:1" } },
  { en: { text: "How sweet are Your words to my taste, sweeter than honey!", ref: "Psalm 119:103" }, es: { text: "¡Cuán dulces son Tus palabras a mi paladar, más que la miel!", ref: "Salmo 119:103" } },
  { en: { text: "The unfolding of Your words gives light.", ref: "Psalm 119:130" }, es: { text: "La exposición de Tus palabras alumbra.", ref: "Salmo 119:130" } },
  { en: { text: "All Scripture is God-breathed and useful for teaching.", ref: "2 Timothy 3:16" }, es: { text: "Toda la Escritura es inspirada por Dios y útil para enseñar.", ref: "2 Timoteo 3:16" } },
  { en: { text: "Heaven and earth will pass away, but My words will never pass.", ref: "Matthew 24:35" }, es: { text: "El cielo y la tierra pasarán, pero Mis palabras no pasarán.", ref: "Mateo 24:35" } },
  { en: { text: "Man shall not live by bread alone, but by every word of God.", ref: "Matthew 4:4" }, es: { text: "No solo de pan vivirá el hombre, sino de toda palabra de Dios.", ref: "Mateo 4:4" } },
  { en: { text: "Let the word of Christ dwell in you richly.", ref: "Colossians 3:16" }, es: { text: "Que la palabra de Cristo more en ustedes con abundancia.", ref: "Colosenses 3:16" } },
  { en: { text: "The word of God is alive and active, sharper than any sword.", ref: "Hebrews 4:12" }, es: { text: "La palabra de Dios es viva y eficaz, más cortante que toda espada.", ref: "Hebreos 4:12" } },
  { en: { text: "Blessed is the one who reads the words of this prophecy.", ref: "Revelation 1:3" }, es: { text: "Bienaventurado el que lee las palabras de esta profecía.", ref: "Apocalipsis 1:3" } },
  // ── June ──
  { en: { text: "As a father has compassion on his children.", ref: "Psalm 103:13" }, es: { text: "Como el padre se compadece de sus hijos.", ref: "Salmo 103:13" } },
  { en: { text: "Fathers, do not exasperate your children.", ref: "Ephesians 6:4" }, es: { text: "Padres, no exasperen a sus hijos.", ref: "Efesios 6:4" } },
  { en: { text: "A wise son brings joy to his father.", ref: "Proverbs 10:1" }, es: { text: "El hijo sabio alegra al padre.", ref: "Proverbios 10:1" } },
  { en: { text: "The Lord disciplines those He loves.", ref: "Proverbs 3:12" }, es: { text: "El Señor disciplina a quien ama.", ref: "Proverbios 3:12" } },
  { en: { text: "Be on your guard; stand firm in the faith.", ref: "1 Corinthians 16:13" }, es: { text: "Estén alerta; permanezcan firmes en la fe.", ref: "1 Corintios 16:13" } },
  { en: { text: "Put on the full armor of God.", ref: "Ephesians 6:11" }, es: { text: "Vístanse con toda la armadura de Dios.", ref: "Efesios 6:11" } },
  { en: { text: "The Lord is my banner.", ref: "Exodus 17:15" }, es: { text: "El Señor es mi estandarte.", ref: "Éxodo 17:15" } },
  { en: { text: "Fight the good fight of faith.", ref: "1 Timothy 6:12" }, es: { text: "Pelea la buena batalla de la fe.", ref: "1 Timoteo 6:12" } },
  { en: { text: "No weapon forged against you will prevail.", ref: "Isaiah 54:17" }, es: { text: "Ninguna arma forjada contra ti prosperará.", ref: "Isaías 54:17" } },
  { en: { text: "Greater is He that is in you than he that is in the world.", ref: "1 John 4:4" }, es: { text: "Mayor es el que está en ustedes que el que está en el mundo.", ref: "1 Juan 4:4" } },
  { en: { text: "Resist the devil, and he will flee from you.", ref: "James 4:7" }, es: { text: "Resistan al diablo, y él huirá de ustedes.", ref: "Santiago 4:7" } },
  { en: { text: "Stand firm then, with the belt of truth buckled around your waist.", ref: "Ephesians 6:14" }, es: { text: "Estén firmes, ceñidos con el cinturón de la verdad.", ref: "Efesios 6:14" } },
  { en: { text: "The Lord is a warrior; the Lord is His name.", ref: "Exodus 15:3" }, es: { text: "El Señor es un guerrero; el Señor es Su nombre.", ref: "Éxodo 15:3" } },
  { en: { text: "He trains my hands for battle.", ref: "Psalm 18:34" }, es: { text: "Él adiestra mis manos para la batalla.", ref: "Salmo 18:34" } },
  { en: { text: "The battle is not yours, but God's.", ref: "2 Chronicles 20:15" }, es: { text: "La batalla no es de ustedes, sino de Dios.", ref: "2 Crónicas 20:15" } },
  { en: { text: "The Lord is my shield, my glory, the lifter of my head.", ref: "Psalm 3:3" }, es: { text: "El Señor es mi escudo, mi gloria, el que levanta mi cabeza.", ref: "Salmo 3:3" } },
  { en: { text: "The Lord goes before you and will be with you.", ref: "Deuteronomy 31:8" }, es: { text: "El Señor va delante de ti y estará contigo.", ref: "Deuteronomio 31:8" } },
  { en: { text: "Do not fear, for I have redeemed you; I have called you by name.", ref: "Isaiah 43:1" }, es: { text: "No temas, porque yo te he redimido; te he llamado por tu nombre.", ref: "Isaías 43:1" } },
  { en: { text: "Surely goodness and love will follow me all the days of my life.", ref: "Psalm 23:6" }, es: { text: "Ciertamente el bien y la misericordia me seguirán todos los días de mi vida.", ref: "Salmo 23:6" } },
  { en: { text: "Even though I walk through the valley of shadow, I fear no evil.", ref: "Psalm 23:4" }, es: { text: "Aunque ande en valle de sombra, no temeré mal alguno.", ref: "Salmo 23:4" } },
  { en: { text: "Weeping may stay for the night, but rejoicing comes in the morning.", ref: "Psalm 30:5" }, es: { text: "Por la noche durará el lloro, pero al amanecer vendrá la alegría.", ref: "Salmo 30:5" } },
  { en: { text: "The Lord has done great things for us, and we are filled with joy.", ref: "Psalm 126:3" }, es: { text: "Grandes cosas ha hecho el Señor por nosotros; estamos llenos de alegría.", ref: "Salmo 126:3" } },
  { en: { text: "Sing to the Lord a new song.", ref: "Psalm 96:1" }, es: { text: "Canten al Señor un cántico nuevo.", ref: "Salmo 96:1" } },
  { en: { text: "Make a joyful noise to the Lord, all the earth!", ref: "Psalm 100:1" }, es: { text: "¡Aclamen al Señor con alegría, toda la tierra!", ref: "Salmo 100:1" } },
  { en: { text: "Enter His gates with thanksgiving and His courts with praise.", ref: "Psalm 100:4" }, es: { text: "Entren por Sus puertas con acción de gracias, por Sus atrios con alabanza.", ref: "Salmo 100:4" } },
  { en: { text: "Clap your hands, all you nations; shout to God with cries of joy.", ref: "Psalm 47:1" }, es: { text: "Aplaudan, pueblos todos; aclamen a Dios con voz de júbilo.", ref: "Salmo 47:1" } },
  { en: { text: "Praise the Lord, my soul, and forget not all His benefits.", ref: "Psalm 103:2" }, es: { text: "Bendice, alma mía, al Señor, y no olvides ninguno de Sus beneficios.", ref: "Salmo 103:2" } },
  { en: { text: "I will give thanks to You, Lord, among all the nations.", ref: "Psalm 57:9" }, es: { text: "Te daré gracias, Señor, entre las naciones.", ref: "Salmo 57:9" } },
  { en: { text: "Rejoice in the Lord always. I will say it again: Rejoice!", ref: "Philippians 4:4" }, es: { text: "Regocíjense en el Señor siempre. Otra vez digo: ¡Regocíjense!", ref: "Filipenses 4:4" } },
  { en: { text: "Shout for joy to the Lord, all the earth.", ref: "Psalm 98:4" }, es: { text: "Aclamen al Señor con alegría, toda la tierra.", ref: "Salmo 98:4" } },
  // ── July ──
  { en: { text: "Blessed is the nation whose God is the Lord.", ref: "Psalm 33:12" }, es: { text: "Bienaventurada la nación cuyo Dios es el Señor.", ref: "Salmo 33:12" } },
  { en: { text: "If My people humble themselves and pray, I will heal their land.", ref: "2 Chronicles 7:14" }, es: { text: "Si Mi pueblo se humilla y ora, sanaré su tierra.", ref: "2 Crónicas 7:14" } },
  { en: { text: "Where the Spirit of the Lord is, there is freedom.", ref: "2 Corinthians 3:17" }, es: { text: "Donde está el Espíritu del Señor, hay libertad.", ref: "2 Corintios 3:17" } },
  { en: { text: "It is for freedom that Christ has set us free.", ref: "Galatians 5:1" }, es: { text: "Para libertad fue que Cristo nos hizo libres.", ref: "Gálatas 5:1" } },
  { en: { text: "You will know the truth, and the truth will set you free.", ref: "John 8:32" }, es: { text: "Conocerán la verdad, y la verdad los hará libres.", ref: "Juan 8:32" } },
  { en: { text: "The Lord sets prisoners free.", ref: "Psalm 146:7" }, es: { text: "El Señor libera a los cautivos.", ref: "Salmo 146:7" } },
  { en: { text: "So if the Son sets you free, you will be free indeed.", ref: "John 8:36" }, es: { text: "Si el Hijo los libera, serán verdaderamente libres.", ref: "Juan 8:36" } },
  { en: { text: "Live as free people, but do not use your freedom as a cover-up.", ref: "1 Peter 2:16" }, es: { text: "Vivan como personas libres, pero no usen su libertad como pretexto.", ref: "1 Pedro 2:16" } },
  { en: { text: "Stand firm and do not let yourselves be burdened again by slavery.", ref: "Galatians 5:1" }, es: { text: "Estén firmes y no se dejen poner de nuevo bajo yugo de esclavitud.", ref: "Gálatas 5:1" } },
  { en: { text: "Know therefore that the Lord your God is God, the faithful God.", ref: "Deuteronomy 7:9" }, es: { text: "Reconoce que el Señor tu Dios es Dios, el Dios fiel.", ref: "Deuteronomio 7:9" } },
  { en: { text: "Hear, O Israel: The Lord our God, the Lord is one.", ref: "Deuteronomy 6:4" }, es: { text: "Oye, Israel: El Señor nuestro Dios, el Señor uno es.", ref: "Deuteronomio 6:4" } },
  { en: { text: "The Lord is slow to anger, abounding in love.", ref: "Numbers 14:18" }, es: { text: "El Señor es lento para la ira y grande en amor.", ref: "Números 14:18" } },
  { en: { text: "For the Lord is good and His love endures forever.", ref: "Psalm 100:5" }, es: { text: "Porque el Señor es bueno y Su amor perdura para siempre.", ref: "Salmo 100:5" } },
  { en: { text: "The Lord reigns, let the earth be glad.", ref: "Psalm 97:1" }, es: { text: "El Señor reina; regocíjese la tierra.", ref: "Salmo 97:1" } },
  { en: { text: "How great is Your goodness, stored up for those who fear You.", ref: "Psalm 31:19" }, es: { text: "¡Cuán grande es Tu bondad, guardada para los que te temen!", ref: "Salmo 31:19" } },
  { en: { text: "From everlasting to everlasting the Lord's love is with those who fear Him.", ref: "Psalm 103:17" }, es: { text: "Desde la eternidad hasta la eternidad el amor del Señor está con los que le temen.", ref: "Salmo 103:17" } },
  { en: { text: "The Lord is exalted over all the nations.", ref: "Psalm 113:4" }, es: { text: "El Señor está exaltado sobre todas las naciones.", ref: "Salmo 113:4" } },
  { en: { text: "Great is our Lord and mighty in power.", ref: "Psalm 147:5" }, es: { text: "Grande es nuestro Señor y poderoso en fuerza.", ref: "Salmo 147:5" } },
  { en: { text: "The Lord is King forever and ever.", ref: "Psalm 10:16" }, es: { text: "El Señor es Rey eternamente y para siempre.", ref: "Salmo 10:16" } },
  { en: { text: "Who is the King of glory? The Lord strong and mighty.", ref: "Psalm 24:8" }, es: { text: "¿Quién es el Rey de gloria? El Señor fuerte y poderoso.", ref: "Salmo 24:8" } },
  { en: { text: "For the Lord Most High is awesome, the great King over all.", ref: "Psalm 47:2" }, es: { text: "Porque el Señor Altísimo es temible, el gran Rey sobre toda la tierra.", ref: "Salmo 47:2" } },
  { en: { text: "He counts the number of the stars; He calls them each by name.", ref: "Psalm 147:4" }, es: { text: "Él cuenta el número de las estrellas; a cada una la llama por su nombre.", ref: "Salmo 147:4" } },
  { en: { text: "By the word of the Lord the heavens were made.", ref: "Psalm 33:6" }, es: { text: "Por la palabra del Señor fueron hechos los cielos.", ref: "Salmo 33:6" } },
  { en: { text: "The Lord looks down from heaven and sees all mankind.", ref: "Psalm 33:13" }, es: { text: "El Señor mira desde los cielos y ve a toda la humanidad.", ref: "Salmo 33:13" } },
  { en: { text: "Our God is in heaven; He does whatever pleases Him.", ref: "Psalm 115:3" }, es: { text: "Nuestro Dios está en los cielos; todo lo que quiso ha hecho.", ref: "Salmo 115:3" } },
  { en: { text: "I lift up my eyes to the mountains — where does my help come from?", ref: "Psalm 121:1" }, es: { text: "Alzo mis ojos a los montes — ¿de dónde vendrá mi socorro?", ref: "Salmo 121:1" } },
  { en: { text: "My help comes from the Lord, the Maker of heaven and earth.", ref: "Psalm 121:2" }, es: { text: "Mi socorro viene del Señor, que hizo los cielos y la tierra.", ref: "Salmo 121:2" } },
  // ── August ──
  { en: { text: "Unless the Lord builds the house, the builders labor in vain.", ref: "Psalm 127:1" }, es: { text: "Si el Señor no edifica la casa, en vano trabajan los que la edifican.", ref: "Salmo 127:1" } },
  { en: { text: "Two are better than one, for they have a good return for their labor.", ref: "Ecclesiastes 4:9" }, es: { text: "Más valen dos que uno, porque tienen mejor recompensa por su trabajo.", ref: "Eclesiastés 4:9" } },
  { en: { text: "Whatever you do, work at it with all your heart, as for the Lord.", ref: "Colossians 3:23" }, es: { text: "Todo lo que hagan, háganlo de corazón, como para el Señor.", ref: "Colosenses 3:23" } },
  { en: { text: "Lazy hands make for poverty, but diligent hands bring wealth.", ref: "Proverbs 10:4" }, es: { text: "Las manos perezosas traen pobreza, pero las manos diligentes traen riqueza.", ref: "Proverbios 10:4" } },
  { en: { text: "The plans of the diligent lead to profit.", ref: "Proverbs 21:5" }, es: { text: "Los planes del diligente llevan a la abundancia.", ref: "Proverbios 21:5" } },
  { en: { text: "Do not merely listen to the word — do what it says.", ref: "James 1:22" }, es: { text: "No solo escuchen la palabra — pongan en práctica lo que dice.", ref: "Santiago 1:22" } },
  { en: { text: "Faith by itself, if it is not accompanied by action, is dead.", ref: "James 2:17" }, es: { text: "La fe por sí sola, si no va acompañada de obras, está muerta.", ref: "Santiago 2:17" } },
  { en: { text: "Whatever your hand finds to do, do it with all your might.", ref: "Ecclesiastes 9:10" }, es: { text: "Todo lo que tu mano halle para hacer, hazlo con todas tus fuerzas.", ref: "Eclesiastés 9:10" } },
  { en: { text: "The harvest is plentiful, but the workers are few.", ref: "Matthew 9:37" }, es: { text: "La cosecha es mucha, pero los obreros son pocos.", ref: "Mateo 9:37" } },
  { en: { text: "Well done, good and faithful servant!", ref: "Matthew 25:21" }, es: { text: "¡Bien hecho, buen siervo y fiel!", ref: "Mateo 25:21" } },
  { en: { text: "For we are God's handiwork, created to do good works.", ref: "Ephesians 2:10" }, es: { text: "Somos hechura de Dios, creados para buenas obras.", ref: "Efesios 2:10" } },
  { en: { text: "Let us not become weary in doing good.", ref: "Galatians 6:9" }, es: { text: "No nos cansemos de hacer el bien.", ref: "Gálatas 6:9" } },
  { en: { text: "Each of you should use whatever gift you have to serve others.", ref: "1 Peter 4:10" }, es: { text: "Cada uno use el don que ha recibido para servir a los demás.", ref: "1 Pedro 4:10" } },
  { en: { text: "Be steadfast, immovable, always abounding in the work of the Lord.", ref: "1 Corinthians 15:58" }, es: { text: "Sean firmes, constantes, creciendo siempre en la obra del Señor.", ref: "1 Corintios 15:58" } },
  { en: { text: "Whatever is true, noble, right, pure — think about such things.", ref: "Philippians 4:8" }, es: { text: "Todo lo que es verdadero, noble, justo, puro — piensen en estas cosas.", ref: "Filipenses 4:8" } },
  { en: { text: "The mind governed by the Spirit is life and peace.", ref: "Romans 8:6" }, es: { text: "La mente gobernada por el Espíritu es vida y paz.", ref: "Romanos 8:6" } },
  { en: { text: "Take captive every thought to make it obedient to Christ.", ref: "2 Corinthians 10:5" }, es: { text: "Llevar cautivo todo pensamiento a la obediencia a Cristo.", ref: "2 Corintios 10:5" } },
  { en: { text: "Guard your heart, for everything you do flows from it.", ref: "Proverbs 4:23" }, es: { text: "Guarda tu corazón, porque de él mana la vida.", ref: "Proverbios 4:23" } },
  { en: { text: "Search me, God, and know my heart.", ref: "Psalm 139:23" }, es: { text: "Examíname, oh Dios, y conoce mi corazón.", ref: "Salmo 139:23" } },
  { en: { text: "Blessed are the peacemakers, for they will be called children of God.", ref: "Matthew 5:9" }, es: { text: "Bienaventurados los pacificadores, porque serán llamados hijos de Dios.", ref: "Mateo 5:9" } },
  { en: { text: "If it is possible, live at peace with everyone.", ref: "Romans 12:18" }, es: { text: "Si es posible, vivan en paz con todos.", ref: "Romanos 12:18" } },
  { en: { text: "Peace I leave with you; My peace I give you.", ref: "John 14:27" }, es: { text: "La paz les dejo, Mi paz les doy.", ref: "Juan 14:27" } },
  { en: { text: "The peace of God will guard your hearts and minds.", ref: "Philippians 4:7" }, es: { text: "La paz de Dios guardará sus corazones y sus mentes.", ref: "Filipenses 4:7" } },
  { en: { text: "He Himself is our peace.", ref: "Ephesians 2:14" }, es: { text: "Él mismo es nuestra paz.", ref: "Efesios 2:14" } },
  { en: { text: "Blessed are those who hunger and thirst for righteousness.", ref: "Matthew 5:6" }, es: { text: "Bienaventurados los que tienen hambre y sed de justicia.", ref: "Mateo 5:6" } },
  { en: { text: "The Lord is righteous in all His ways and faithful in all He does.", ref: "Psalm 145:17" }, es: { text: "El Señor es justo en todos Sus caminos y fiel en todas Sus obras.", ref: "Salmo 145:17" } },
  { en: { text: "The eyes of the Lord are on the righteous.", ref: "Psalm 34:15" }, es: { text: "Los ojos del Señor están sobre los justos.", ref: "Salmo 34:15" } },
  // ── September ──
  { en: { text: "To everything there is a season, and a time for every purpose.", ref: "Ecclesiastes 3:1" }, es: { text: "Todo tiene su tiempo, y todo lo que se quiere bajo el cielo tiene su hora.", ref: "Eclesiastés 3:1" } },
  { en: { text: "He has made everything beautiful in its time.", ref: "Ecclesiastes 3:11" }, es: { text: "Todo lo hizo hermoso en su tiempo.", ref: "Eclesiastés 3:11" } },
  { en: { text: "Be very careful how you live — not as unwise but as wise.", ref: "Ephesians 5:15" }, es: { text: "Tengan cuidado cómo viven — no como necios sino como sabios.", ref: "Efesios 5:15" } },
  { en: { text: "Making the best use of the time, because the days are evil.", ref: "Ephesians 5:16" }, es: { text: "Aprovechando bien el tiempo, porque los días son malos.", ref: "Efesios 5:16" } },
  { en: { text: "Teach us to number our days, that we may gain a heart of wisdom.", ref: "Psalm 90:12" }, es: { text: "Enséñanos a contar nuestros días para que adquiramos un corazón sabio.", ref: "Salmo 90:12" } },
  { en: { text: "The fear of the Lord is the beginning of wisdom.", ref: "Proverbs 9:10" }, es: { text: "El temor del Señor es el principio de la sabiduría.", ref: "Proverbios 9:10" } },
  { en: { text: "If any of you lacks wisdom, let him ask God.", ref: "James 1:5" }, es: { text: "Si a alguno le falta sabiduría, pídala a Dios.", ref: "Santiago 1:5" } },
  { en: { text: "For the Lord gives wisdom; from His mouth come knowledge.", ref: "Proverbs 2:6" }, es: { text: "El Señor da sabiduría; de Su boca vienen el conocimiento.", ref: "Proverbios 2:6" } },
  { en: { text: "The beginning of wisdom is this: Get wisdom.", ref: "Proverbs 4:7" }, es: { text: "El principio de la sabiduría es: Adquiere sabiduría.", ref: "Proverbios 4:7" } },
  { en: { text: "Blessed is the one who finds wisdom.", ref: "Proverbs 3:13" }, es: { text: "Bienaventurado el que halla la sabiduría.", ref: "Proverbios 3:13" } },
  { en: { text: "How much better to get wisdom than gold!", ref: "Proverbs 16:16" }, es: { text: "¡Cuánto mejor es adquirir sabiduría que oro!", ref: "Proverbios 16:16" } },
  { en: { text: "Wisdom is more precious than rubies.", ref: "Proverbs 8:11" }, es: { text: "La sabiduría es más preciosa que los rubíes.", ref: "Proverbios 8:11" } },
  { en: { text: "Plans fail for lack of counsel, but with many advisers they succeed.", ref: "Proverbs 15:22" }, es: { text: "Sin consejo los planes fracasan, pero con muchos consejeros tienen éxito.", ref: "Proverbios 15:22" } },
  { en: { text: "Listen to advice and accept discipline.", ref: "Proverbs 19:20" }, es: { text: "Escucha el consejo y acepta la disciplina.", ref: "Proverbios 19:20" } },
  { en: { text: "Trust in the Lord and do good.", ref: "Psalm 37:3" }, es: { text: "Confía en el Señor y haz el bien.", ref: "Salmo 37:3" } },
  { en: { text: "Do not let your hearts be troubled. Trust in God; trust also in Me.", ref: "John 14:1" }, es: { text: "No se turbe su corazón. Confíen en Dios; confíen también en Mí.", ref: "Juan 14:1" } },
  { en: { text: "Now faith is confidence in what we hope for.", ref: "Hebrews 11:1" }, es: { text: "La fe es la certeza de lo que se espera.", ref: "Hebreos 11:1" } },
  { en: { text: "Without faith it is impossible to please God.", ref: "Hebrews 11:6" }, es: { text: "Sin fe es imposible agradar a Dios.", ref: "Hebreos 11:6" } },
  { en: { text: "Faith comes from hearing the message.", ref: "Romans 10:17" }, es: { text: "La fe viene por el oír el mensaje.", ref: "Romanos 10:17" } },
  { en: { text: "We walk by faith, not by sight.", ref: "2 Corinthians 5:7" }, es: { text: "Porque por fe andamos, no por vista.", ref: "2 Corintios 5:7" } },
  { en: { text: "The righteous will live by faith.", ref: "Romans 1:17" }, es: { text: "El justo vivirá por la fe.", ref: "Romanos 1:17" } },
  { en: { text: "If you have faith as small as a mustard seed.", ref: "Matthew 17:20" }, es: { text: "Si tienen fe tan pequeña como un grano de mostaza.", ref: "Mateo 17:20" } },
  { en: { text: "Lord, I believe; help my unbelief!", ref: "Mark 9:24" }, es: { text: "¡Creo, Señor; ayuda mi incredulidad!", ref: "Marcos 9:24" } },
  { en: { text: "Fix our eyes on Jesus, the pioneer and perfecter of faith.", ref: "Hebrews 12:2" }, es: { text: "Puestos los ojos en Jesús, el autor y consumador de la fe.", ref: "Hebreos 12:2" } },
  { en: { text: "By grace you have been saved, through faith.", ref: "Ephesians 2:8" }, es: { text: "Por gracia han sido salvados mediante la fe.", ref: "Efesios 2:8" } },
  { en: { text: "Be faithful, even to the point of death, and I will give you the crown.", ref: "Revelation 2:10" }, es: { text: "Sé fiel hasta la muerte, y yo te daré la corona de la vida.", ref: "Apocalipsis 2:10" } },
  // ── October ──
  { en: { text: "Do not be overcome by evil, but overcome evil with good.", ref: "Romans 12:21" }, es: { text: "No sean vencidos por el mal, sino venzan el mal con el bien.", ref: "Romanos 12:21" } },
  { en: { text: "The Lord is my hiding place; You will protect me from trouble.", ref: "Psalm 32:7" }, es: { text: "Tú eres mi escondite; me protegerás de la angustia.", ref: "Salmo 32:7" } },
  { en: { text: "God has not given us a spirit of fear, but of power.", ref: "2 Timothy 1:7" }, es: { text: "Dios no nos ha dado un espíritu de temor, sino de poder.", ref: "2 Timoteo 1:7" } },
  { en: { text: "When you pass through the waters, I will be with you.", ref: "Isaiah 43:2" }, es: { text: "Cuando pases por las aguas, yo estaré contigo.", ref: "Isaías 43:2" } },
  { en: { text: "Fear not, for I am with you; be not dismayed.", ref: "Isaiah 41:10" }, es: { text: "No temas, porque yo estoy contigo; no desmayes.", ref: "Isaías 41:10" } },
  { en: { text: "The Lord is on my side; I will not fear.", ref: "Psalm 118:6" }, es: { text: "El Señor está de mi lado; no temeré.", ref: "Salmo 118:6" } },
  { en: { text: "In God I trust and am not afraid.", ref: "Psalm 56:4" }, es: { text: "En Dios confío y no tengo miedo.", ref: "Salmo 56:4" } },
  { en: { text: "The angel of the Lord encamps around those who fear Him.", ref: "Psalm 34:7" }, es: { text: "El ángel del Señor acampa alrededor de los que le temen.", ref: "Salmo 34:7" } },
  { en: { text: "He will command His angels concerning you.", ref: "Psalm 91:11" }, es: { text: "Él dará órdenes a Sus ángeles acerca de ti.", ref: "Salmo 91:11" } },
  { en: { text: "For He will deliver you from the snare of the fowler.", ref: "Psalm 91:3" }, es: { text: "Él te librará del lazo del cazador.", ref: "Salmo 91:3" } },
  { en: { text: "He who dwells in the shelter of the Most High will rest in His shadow.", ref: "Psalm 91:1" }, es: { text: "El que habita al abrigo del Altísimo descansará bajo Su sombra.", ref: "Salmo 91:1" } },
  { en: { text: "I will say of the Lord, He is my refuge and my fortress.", ref: "Psalm 91:2" }, es: { text: "Diré del Señor: Él es mi refugio y mi fortaleza.", ref: "Salmo 91:2" } },
  { en: { text: "The Lord is a sun and shield; He bestows favor and honor.", ref: "Psalm 84:11" }, es: { text: "El Señor es sol y escudo; da gracia y gloria.", ref: "Salmo 84:11" } },
  { en: { text: "The Lord preserves all who love Him.", ref: "Psalm 145:20" }, es: { text: "El Señor protege a todos los que lo aman.", ref: "Salmo 145:20" } },
  { en: { text: "The name of the Lord is a strong tower.", ref: "Proverbs 18:10" }, es: { text: "El nombre del Señor es torre fuerte.", ref: "Proverbios 18:10" } },
  { en: { text: "Blessed is the man who trusts in the Lord.", ref: "Jeremiah 17:7" }, es: { text: "Bendito el hombre que confía en el Señor.", ref: "Jeremías 17:7" } },
  { en: { text: "I sought the Lord, and He answered me.", ref: "Psalm 34:4" }, es: { text: "Busqué al Señor, y Él me respondió.", ref: "Salmo 34:4" } },
  { en: { text: "Call to Me and I will answer you.", ref: "Jeremiah 33:3" }, es: { text: "Clama a Mí y Yo te responderé.", ref: "Jeremías 33:3" } },
  { en: { text: "The Lord hears the needy.", ref: "Psalm 69:33" }, es: { text: "El Señor oye a los necesitados.", ref: "Salmo 69:33" } },
  { en: { text: "Before they call I will answer; while they speak I will hear.", ref: "Isaiah 65:24" }, es: { text: "Antes que clamen, yo responderé; mientras aún hablan, yo oiré.", ref: "Isaías 65:24" } },
  { en: { text: "The prayer of a righteous person is powerful and effective.", ref: "James 5:16" }, es: { text: "La oración del justo es poderosa y eficaz.", ref: "Santiago 5:16" } },
  { en: { text: "Pray without ceasing.", ref: "1 Thessalonians 5:17" }, es: { text: "Oren sin cesar.", ref: "1 Tesalonicenses 5:17" } },
  { en: { text: "Let us approach God's throne of grace with confidence.", ref: "Hebrews 4:16" }, es: { text: "Acerquémonos con confianza al trono de la gracia de Dios.", ref: "Hebreos 4:16" } },
  { en: { text: "If you remain in Me and My words remain in you, ask whatever you wish.", ref: "John 15:7" }, es: { text: "Si permanecen en Mí y Mis palabras permanecen en ustedes, pidan lo que quieran.", ref: "Juan 15:7" } },
  { en: { text: "Watch and pray so that you will not fall into temptation.", ref: "Matthew 26:41" }, es: { text: "Velen y oren para que no caigan en tentación.", ref: "Mateo 26:41" } },
  { en: { text: "Devote yourselves to prayer, being watchful and thankful.", ref: "Colossians 4:2" }, es: { text: "Dedíquense a la oración, velando con gratitud.", ref: "Colosenses 4:2" } },
  { en: { text: "The Spirit Himself intercedes for us through wordless groans.", ref: "Romans 8:26" }, es: { text: "El Espíritu mismo intercede por nosotros con gemidos indecibles.", ref: "Romanos 8:26" } },
  { en: { text: "Evening, morning and noon I cry out, and He hears my voice.", ref: "Psalm 55:17" }, es: { text: "Tarde, mañana y mediodía clamo, y Él oye mi voz.", ref: "Salmo 55:17" } },
  // ── November ──
  { en: { text: "Give thanks in all circumstances; for this is God's will.", ref: "1 Thessalonians 5:18" }, es: { text: "Den gracias en todo, porque esta es la voluntad de Dios.", ref: "1 Tesalonicenses 5:18" } },
  { en: { text: "Enter His gates with thanksgiving.", ref: "Psalm 100:4" }, es: { text: "Entren por Sus puertas con acción de gracias.", ref: "Salmo 100:4" } },
  { en: { text: "Let them give thanks to the Lord for His unfailing love.", ref: "Psalm 107:8" }, es: { text: "Den gracias al Señor por Su amor inagotable.", ref: "Salmo 107:8" } },
  { en: { text: "Give thanks to the Lord, for He is good.", ref: "Psalm 136:1" }, es: { text: "Den gracias al Señor, porque Él es bueno.", ref: "Salmo 136:1" } },
  { en: { text: "I will give thanks to the Lord because of His righteousness.", ref: "Psalm 7:17" }, es: { text: "Daré gracias al Señor por Su justicia.", ref: "Salmo 7:17" } },
  { en: { text: "Thanks be to God for His indescribable gift!", ref: "2 Corinthians 9:15" }, es: { text: "¡Gracias a Dios por Su don inefable!", ref: "2 Corintios 9:15" } },
  { en: { text: "Thanks be to God! He gives us the victory through our Lord.", ref: "1 Corinthians 15:57" }, es: { text: "¡Gracias a Dios! Él nos da la victoria por medio de nuestro Señor.", ref: "1 Corintios 15:57" } },
  { en: { text: "Overflow with thankfulness.", ref: "Colossians 2:7" }, es: { text: "Rebosen de gratitud.", ref: "Colosenses 2:7" } },
  { en: { text: "I will give You thanks, for You answered me.", ref: "Psalm 118:21" }, es: { text: "Te daré gracias, porque me respondiste.", ref: "Salmo 118:21" } },
  { en: { text: "Praise the Lord, my soul; all my inmost being, praise His holy name.", ref: "Psalm 103:1" }, es: { text: "Bendice, alma mía, al Señor; todo mi ser bendiga Su santo nombre.", ref: "Salmo 103:1" } },
  { en: { text: "I will extol the Lord at all times; His praise will always be on my lips.", ref: "Psalm 34:1" }, es: { text: "Bendeciré al Señor en todo tiempo; Su alabanza estará siempre en mis labios.", ref: "Salmo 34:1" } },
  { en: { text: "From the rising of the sun to its setting, praise the name of the Lord.", ref: "Psalm 113:3" }, es: { text: "Desde la salida del sol hasta su ocaso, sea alabado el nombre del Señor.", ref: "Salmo 113:3" } },
  { en: { text: "Oh give thanks to the Lord; call upon His name.", ref: "Psalm 105:1" }, es: { text: "Den gracias al Señor; invoquen Su nombre.", ref: "Salmo 105:1" } },
  { en: { text: "Bless the Lord, O my soul, and forget not all His benefits.", ref: "Psalm 103:2" }, es: { text: "Bendice, alma mía, al Señor, y no olvides ninguno de Sus beneficios.", ref: "Salmo 103:2" } },
  { en: { text: "The Lord is my portion; therefore I will wait for Him.", ref: "Lamentations 3:24" }, es: { text: "El Señor es mi porción; por tanto, en Él esperaré.", ref: "Lamentaciones 3:24" } },
  { en: { text: "I will be glad and rejoice in Your love.", ref: "Psalm 31:7" }, es: { text: "Me alegraré y me regocijaré en Tu amor.", ref: "Salmo 31:7" } },
  { en: { text: "The Lord takes delight in His people.", ref: "Psalm 149:4" }, es: { text: "El Señor se complace en Su pueblo.", ref: "Salmo 149:4" } },
  { en: { text: "It is good to praise the Lord and make music to Your name.", ref: "Psalm 92:1" }, es: { text: "Bueno es alabar al Señor y cantar a Tu nombre.", ref: "Salmo 92:1" } },
  { en: { text: "I will sing to the Lord all my life.", ref: "Psalm 104:33" }, es: { text: "Cantaré al Señor toda mi vida.", ref: "Salmo 104:33" } },
  { en: { text: "My mouth will speak in praise of the Lord.", ref: "Psalm 145:21" }, es: { text: "Mi boca proclamará la alabanza del Señor.", ref: "Salmo 145:21" } },
  { en: { text: "Sing to the Lord, for He has done glorious things.", ref: "Isaiah 12:5" }, es: { text: "Canten al Señor, porque ha hecho cosas gloriosas.", ref: "Isaías 12:5" } },
  { en: { text: "You are worthy, our Lord and God, to receive glory.", ref: "Revelation 4:11" }, es: { text: "Digno eres, Señor y Dios nuestro, de recibir la gloria.", ref: "Apocalipsis 4:11" } },
  { en: { text: "Holy, holy, holy is the Lord Almighty.", ref: "Isaiah 6:3" }, es: { text: "Santo, santo, santo es el Señor Todopoderoso.", ref: "Isaías 6:3" } },
  { en: { text: "Worthy is the Lamb, who was slain.", ref: "Revelation 5:12" }, es: { text: "Digno es el Cordero que fue inmolado.", ref: "Apocalipsis 5:12" } },
  { en: { text: "The Lord is clothed in majesty.", ref: "Psalm 93:1" }, es: { text: "El Señor está vestido de majestad.", ref: "Salmo 93:1" } },
  { en: { text: "Splendor and majesty are before Him.", ref: "Psalm 96:6" }, es: { text: "Esplendor y majestad están delante de Él.", ref: "Salmo 96:6" } },
  { en: { text: "O Lord, our Lord, how majestic is Your name in all the earth!", ref: "Psalm 8:1" }, es: { text: "¡Oh Señor, Señor nuestro, cuán majestuoso es Tu nombre en toda la tierra!", ref: "Salmo 8:1" } },
  { en: { text: "One generation commends Your works to another.", ref: "Psalm 145:4" }, es: { text: "Una generación celebrará Tus obras ante otra generación.", ref: "Salmo 145:4" } },
  { en: { text: "Declare His glory among the nations.", ref: "Psalm 96:3" }, es: { text: "Proclamen Su gloria entre las naciones.", ref: "Salmo 96:3" } },
  // ── December ──
  { en: { text: "For to us a child is born, to us a son is given.", ref: "Isaiah 9:6" }, es: { text: "Porque un niño nos es nacido, un hijo nos es dado.", ref: "Isaías 9:6" } },
  { en: { text: "He will be called Wonderful Counselor, Mighty God.", ref: "Isaiah 9:6" }, es: { text: "Se llamará Consejero Admirable, Dios Fuerte.", ref: "Isaías 9:6" } },
  { en: { text: "The people walking in darkness have seen a great light.", ref: "Isaiah 9:2" }, es: { text: "El pueblo que andaba en tinieblas vio gran luz.", ref: "Isaías 9:2" } },
  { en: { text: "The virgin will conceive and give birth to a son — Immanuel.", ref: "Isaiah 7:14" }, es: { text: "La virgen concebirá y dará a luz un hijo — Emanuel.", ref: "Isaías 7:14" } },
  { en: { text: "But you, Bethlehem, out of you will come a ruler over Israel.", ref: "Micah 5:2" }, es: { text: "Pero tú, Belén, de ti saldrá un gobernante de Israel.", ref: "Miqueas 5:2" } },
  { en: { text: "Glory to God in the highest heaven, and on earth peace.", ref: "Luke 2:14" }, es: { text: "Gloria a Dios en las alturas, y en la tierra paz.", ref: "Lucas 2:14" } },
  { en: { text: "Today in the town of David a Savior has been born to you.", ref: "Luke 2:11" }, es: { text: "Hoy en la ciudad de David les ha nacido un Salvador.", ref: "Lucas 2:11" } },
  { en: { text: "Do not be afraid. I bring you good news that will cause great joy.", ref: "Luke 2:10" }, es: { text: "No teman. Les traigo buenas nuevas de gran gozo.", ref: "Lucas 2:10" } },
  { en: { text: "She gave birth to her firstborn, a son, and wrapped Him in cloths.", ref: "Luke 2:7" }, es: { text: "Dio a luz a su hijo primogénito, y lo envolvió en pañales.", ref: "Lucas 2:7" } },
  { en: { text: "They saw the child with His mother Mary, and they bowed down.", ref: "Matthew 2:11" }, es: { text: "Vieron al niño con Su madre María, y se postraron.", ref: "Mateo 2:11" } },
  { en: { text: "The Word became flesh and made His dwelling among us.", ref: "John 1:14" }, es: { text: "El Verbo se hizo carne y habitó entre nosotros.", ref: "Juan 1:14" } },
  { en: { text: "In Him was life, and that life was the light of all mankind.", ref: "John 1:4" }, es: { text: "En Él estaba la vida, y la vida era la luz de los hombres.", ref: "Juan 1:4" } },
  { en: { text: "The true light that gives light to everyone was coming into the world.", ref: "John 1:9" }, es: { text: "La luz verdadera que alumbra a todo hombre venía a este mundo.", ref: "Juan 1:9" } },
  { en: { text: "I am the light of the world.", ref: "John 8:12" }, es: { text: "Yo soy la luz del mundo.", ref: "Juan 8:12" } },
  { en: { text: "For God did not send His Son to condemn the world.", ref: "John 3:17" }, es: { text: "Dios no envió a Su Hijo para condenar al mundo.", ref: "Juan 3:17" } },
  { en: { text: "For the wages of sin is death, but the gift of God is eternal life.", ref: "Romans 6:23" }, es: { text: "La paga del pecado es muerte, pero el don de Dios es vida eterna.", ref: "Romanos 6:23" } },
  { en: { text: "Every good gift and every perfect gift is from above.", ref: "James 1:17" }, es: { text: "Toda buena dádiva y todo don perfecto viene de lo alto.", ref: "Santiago 1:17" } },
  { en: { text: "Thanks be to God for His indescribable gift!", ref: "2 Corinthians 9:15" }, es: { text: "¡Gracias a Dios por Su don inefable!", ref: "2 Corintios 9:15" } },
  { en: { text: "God so loved the world that He gave His one and only Son.", ref: "John 3:16" }, es: { text: "De tal manera amó Dios al mundo que dio a Su Hijo unigénito.", ref: "Juan 3:16" } },
  { en: { text: "The gift of God is eternal life in Christ Jesus our Lord.", ref: "Romans 6:23" }, es: { text: "El don de Dios es vida eterna en Cristo Jesús nuestro Señor.", ref: "Romanos 6:23" } },
  { en: { text: "And the angel said to them, 'Fear not.'", ref: "Luke 2:10" }, es: { text: "Y el ángel les dijo: 'No teman.'", ref: "Lucas 2:10" } },
  { en: { text: "A star will come out of Jacob; a scepter will rise out of Israel.", ref: "Numbers 24:17" }, es: { text: "Una estrella saldrá de Jacob; un cetro se levantará de Israel.", ref: "Números 24:17" } },
  { en: { text: "Where is the one who has been born king of the Jews?", ref: "Matthew 2:2" }, es: { text: "¿Dónde está el que ha nacido rey de los judíos?", ref: "Mateo 2:2" } },
  { en: { text: "They opened their treasures and presented Him with gifts.", ref: "Matthew 2:11" }, es: { text: "Abrieron sus tesoros y le ofrecieron presentes.", ref: "Mateo 2:11" } },
  { en: { text: "God is with us.", ref: "Isaiah 8:10" }, es: { text: "Dios está con nosotros.", ref: "Isaías 8:10" } },
  { en: { text: "Behold, I am making all things new.", ref: "Revelation 21:5" }, es: { text: "He aquí, Yo hago nuevas todas las cosas.", ref: "Apocalipsis 21:5" } },
  { en: { text: "He will wipe every tear from their eyes.", ref: "Revelation 21:4" }, es: { text: "Enjugará toda lágrima de sus ojos.", ref: "Apocalipsis 21:4" } },
  { en: { text: "I am the Alpha and the Omega, the beginning and the end.", ref: "Revelation 21:6" }, es: { text: "Yo soy el Alfa y la Omega, el principio y el fin.", ref: "Apocalipsis 21:6" } },
  { en: { text: "His faithfulness continues through all generations.", ref: "Psalm 100:5" }, es: { text: "Su fidelidad permanece por todas las generaciones.", ref: "Salmo 100:5" } },
  { en: { text: "Jesus Christ is the same yesterday and today and forever.", ref: "Hebrews 13:8" }, es: { text: "Jesucristo es el mismo ayer, hoy y por los siglos.", ref: "Hebreos 13:8" } },
  { en: { text: "See, I am doing a new thing! Do you not perceive it?", ref: "Isaiah 43:19" }, es: { text: "¡He aquí que hago cosa nueva! ¿No la perciben?", ref: "Isaías 43:19" } },
];

/** Returns the verse for a given date (defaults to today) in the requested language. */
export function getVerseOfTheDay(date: Date = new Date(), lang: "en" | "es" = "en"): { text: string; ref: string } {
  const start = new Date(date.getFullYear(), 0, 0);
  const diff = date.getTime() - start.getTime();
  const dayOfYear = Math.floor(diff / 86_400_000);
  const index = (dayOfYear - 1 + 365) % DAILY_VERSES.length;
  return DAILY_VERSES[index][lang];
}
