-- New Home playlists that show catalog depth. Safe to re-run.

INSERT OR IGNORE INTO playlists (id, app_id, name, description, playlist_type, is_featured, sort_order) VALUES
  ('pl-psalms', 'bible-tea', 'Songs After Midnight', 'The psalms when the house is quiet — fear, praise, and the kind of honesty you only say in the dark.', 'thematic', 1, 40),
  ('pl-end-times', 'bible-tea', 'After the Last Page', 'Horsemen, falling cities, and a new earth. The Bible does not whisper the ending.', 'thematic', 1, 41),
  ('pl-job', 'bible-tea', 'When God Goes Quiet', 'Job lost everything and still wanted an answer. This is the Bible at its most human.', 'thematic', 1, 42),
  ('pl-letters', 'bible-tea', 'Ink & Prison', 'Letters written in chains and on the road — love, armor, and finishing the race.', 'thematic', 1, 43),
  ('pl-late-prophets', 'bible-tea', 'The Last Voices', 'Isaiah, Jeremiah, Ezekiel, Hosea. Visions, clay, dry bones, and a love that will not quit.', 'thematic', 1, 44),
  ('pl-holy-ground', 'bible-tea', 'Holy Ground', 'Priests, feasts, vows, and the rules that were supposed to make a people different.', 'thematic', 1, 45),
  ('pl-four-gospels', 'bible-tea', 'The Four Witnesses', 'Matthew, Mark, Luke, John — the stories that did not fit the highlight reel.', 'thematic', 1, 46),
  ('pl-wisdom', 'bible-tea', 'Street-Smart Scripture', 'Proverbs that still read like someone is talking across the table.', 'thematic', 1, 47);

INSERT OR IGNORE INTO playlist_stories (playlist_id, story_id, sort_order) VALUES
  ('pl-psalms', 'st-david-writes-psalm-23', 1),
  ('pl-psalms', 'st-songs-in-the-night', 2),
  ('pl-psalms', 'st-psalm-51-a-broken-king', 3),
  ('pl-psalms', 'st-psalm-91-gods-protection', 4),
  ('pl-psalms', 'st-psalm-139-fully-known', 5),
  ('pl-psalms', 'st-psalm-150-everything-praise', 6),
  ('pl-end-times', 'st-signs-of-the-end', 1),
  ('pl-end-times', 'st-daniels-visions', 2),
  ('pl-end-times', 'st-johns-exile-and-revelation', 3),
  ('pl-end-times', 'st-letters-to-seven-churches', 4),
  ('pl-end-times', 'st-the-four-horsemen', 5),
  ('pl-end-times', 'st-the-fall-of-babylon', 6),
  ('pl-end-times', 'st-the-new-heaven-and-new-earth', 7),
  ('pl-end-times', 'st-new-heavens-new-earth-isaiah', 8),
  ('pl-job', 'st-jobs-suffering', 1),
  ('pl-job', 'st-jobs-friends-speak', 2),
  ('pl-job', 'st-god-answers-job', 3),
  ('pl-job', 'st-job-restored', 4),
  ('pl-letters', 'st-love-is', 1),
  ('pl-letters', 'st-armor-of-god', 2),
  ('pl-letters', 'st-paul-and-timothy', 3),
  ('pl-letters', 'st-pauls-letter-to-rome', 4),
  ('pl-letters', 'st-james-writes-to-the-church', 5),
  ('pl-letters', 'st-taming-the-tongue', 6),
  ('pl-letters', 'st-faith-without-works', 7),
  ('pl-letters', 'st-peters-final-letter', 8),
  ('pl-letters', 'st-guard-the-truth', 9),
  ('pl-letters', 'st-pauls-last-letter', 10),
  ('pl-letters', 'st-finish-the-race', 11),
  ('pl-late-prophets', 'st-isaiahs-vision', 1),
  ('pl-late-prophets', 'st-isaiahs-call', 2),
  ('pl-late-prophets', 'st-immanuel-prophecy', 3),
  ('pl-late-prophets', 'st-jeremiah-the-weeping-prophet', 4),
  ('pl-late-prophets', 'st-the-potters-clay', 5),
  ('pl-late-prophets', 'st-jeremiah-in-the-cistern', 6),
  ('pl-late-prophets', 'st-the-new-covenant', 7),
  ('pl-late-prophets', 'st-ezekiels-call-and-the-wheel', 8),
  ('pl-late-prophets', 'st-valley-of-dry-bones', 9),
  ('pl-late-prophets', 'st-the-restored-temple', 10),
  ('pl-late-prophets', 'st-hosea-and-gomer', 11),
  ('pl-late-prophets', 'st-israels-unfaithfulness', 12),
  ('pl-late-prophets', 'st-gods-love-wins', 13),
  ('pl-holy-ground', 'st-first-priests', 1),
  ('pl-holy-ground', 'st-offerings', 2),
  ('pl-holy-ground', 'st-clean-unclean', 3),
  ('pl-holy-ground', 'st-atonement', 4),
  ('pl-holy-ground', 'st-holiness', 5),
  ('pl-holy-ground', 'st-feasts', 6),
  ('pl-holy-ground', 'st-sabbath-jubilee-and-justice', 7),
  ('pl-holy-ground', 'st-what-god-really-wants', 8),
  ('pl-holy-ground', 'st-cancel-debts-set-people-free', 9),
  ('pl-holy-ground', 'st-the-ultimate-choice', 10),
  ('pl-holy-ground', 'st-choose-life-or-death', 11),
  ('pl-holy-ground', 'st-blessings-and-curses', 12),
  ('pl-four-gospels', 'st-the-sabbath-showdowns', 1),
  ('pl-four-gospels', 'st-demons-and-accusations', 2),
  ('pl-four-gospels', 'st-john-the-baptist-beheaded', 3),
  ('pl-four-gospels', 'st-feeding-4000', 4),
  ('pl-four-gospels', 'st-peters-big-confession', 5),
  ('pl-four-gospels', 'st-the-transfiguration', 6),
  ('pl-four-gospels', 'st-caesars-coin', 7),
  ('pl-four-gospels', 'st-the-greatest-commandment', 8),
  ('pl-four-gospels', 'st-casting-out-an-evil-spirit', 9),
  ('pl-four-gospels', 'st-legion-and-the-pigs', 10),
  ('pl-four-gospels', 'st-the-purity-debate', 11),
  ('pl-four-gospels', 'st-the-cursed-fig-tree', 12),
  ('pl-four-gospels', 'st-the-miraculous-catch', 13),
  ('pl-four-gospels', 'st-sending-out-72', 14),
  ('pl-four-gospels', 'st-calling-out-the-pharisees', 15),
  ('pl-four-gospels', 'st-john-declares-the-lamb', 16),
  ('pl-four-gospels', 'st-nicodemus-comes-at-night', 17),
  ('pl-four-gospels', 'st-jesus-flips-tables', 18),
  ('pl-four-gospels', 'st-bread-of-life', 19),
  ('pl-four-gospels', 'st-the-festival-showdown', 20),
  ('pl-wisdom', 'st-solomons-proverbs', 1),
  ('pl-wisdom', 'st-the-wise-and-the-foolish', 2),
  ('pl-wisdom', 'st-the-proverbs-31-woman', 3),
  ('pl-wisdom', 'st-solomon', 4),
  ('pl-wisdom', 'st-queen-of-sheba', 5);

UPDATE playlists SET is_featured = 1 WHERE app_id = 'bible-tea' AND id IN ('pl-easter', 'pl-exodus', 'pl-abraham');

INSERT OR REPLACE INTO content_translations (app_id, entity_type, entity_id, locale, field, value) VALUES
  ('bible-tea', 'playlist', 'pl-psalms', 'es', 'name', 'Canciones Después de Medianoche'),
  ('bible-tea', 'playlist', 'pl-psalms', 'es', 'description', 'Los salmos cuando la casa está en silencio.'),
  ('bible-tea', 'playlist', 'pl-end-times', 'es', 'name', 'Después de la Última Página'),
  ('bible-tea', 'playlist', 'pl-end-times', 'es', 'description', 'Jinetes, ciudades que caen y una tierra nueva.'),
  ('bible-tea', 'playlist', 'pl-job', 'es', 'name', 'Cuando Dios Se Queda Callado'),
  ('bible-tea', 'playlist', 'pl-job', 'es', 'description', 'Job lo perdió todo y todavía quería una respuesta.'),
  ('bible-tea', 'playlist', 'pl-letters', 'es', 'name', 'Tinta y Prisión'),
  ('bible-tea', 'playlist', 'pl-letters', 'es', 'description', 'Cartas escritas en cadenas y en el camino.'),
  ('bible-tea', 'playlist', 'pl-late-prophets', 'es', 'name', 'Las Últimas Voces'),
  ('bible-tea', 'playlist', 'pl-late-prophets', 'es', 'description', 'Isaías, Jeremías, Ezequiel, Oseas.'),
  ('bible-tea', 'playlist', 'pl-holy-ground', 'es', 'name', 'Tierra Santa'),
  ('bible-tea', 'playlist', 'pl-holy-ground', 'es', 'description', 'Sacerdotes, fiestas y las reglas que debían hacer distinto a un pueblo.'),
  ('bible-tea', 'playlist', 'pl-four-gospels', 'es', 'name', 'Los Cuatro Testigos'),
  ('bible-tea', 'playlist', 'pl-four-gospels', 'es', 'description', 'Mateo, Marcos, Lucas y Juan — lo que no cabía en los highlights.'),
  ('bible-tea', 'playlist', 'pl-wisdom', 'es', 'name', 'Sabiduría de Calle'),
  ('bible-tea', 'playlist', 'pl-wisdom', 'es', 'description', 'Proverbios que todavía suenan como una conversación de mesa.');
