-- Exclusive playlists: every published story in exactly one playlist.
-- Safe to re-run.

DELETE FROM playlist_stories
WHERE playlist_id IN (SELECT id FROM playlists WHERE app_id = 'bible-tea');

INSERT OR IGNORE INTO playlists (id, app_id, name, description, playlist_type, is_featured, sort_order) VALUES
  ('pl-origins', 'bible-tea', 'Origin Stories', 'The first blood, the first flood, the first tower. How it all started.', 'thematic', 1, 1),
  ('pl-abraham', 'bible-tea', 'Abraham''s Deal', 'A man lies, waits, and almost kills his son because a voice told him to.', 'thematic', 1, 2),
  ('pl-brothers', 'bible-tea', 'Brothers & Blood', 'Jacob steals a blessing. Joseph gets sold. Family dinner, biblical edition.', 'thematic', 1, 3),
  ('pl-exodus', 'bible-tea', 'The Great Escape', 'Slavery, plagues, a sea that splits. The original action movie.', 'thematic', 1, 4),
  ('pl-holy-ground', 'bible-tea', 'Holy Ground', 'Priests, feasts, and the rules that were supposed to make a people different.', 'thematic', 1, 5),
  ('pl-wilderness', 'bible-tea', 'Forty Years Lost', 'Snakes, spies, a talking donkey, and a nation that will not stop complaining.', 'thematic', 1, 6),
  ('pl-last-words', 'bible-tea', 'Moses'' Last Words', 'Before he dies in sight of the land: choose life, or don''t.', 'thematic', 1, 7),
  ('pl-joshua', 'bible-tea', 'Take the Land', 'Jordan, Jericho, the sun stands still. Conquest with no clean hands.', 'thematic', 1, 8),
  ('pl-judges', 'bible-tea', 'No King. No Rules.', 'Tent pegs, reckless vows, Samson. Everyone did what they wanted.', 'thematic', 1, 9),
  ('pl-samuel', 'bible-tea', 'Before the Crown', 'A boy, a giant, a jealous king, and a witch at Endor.', 'thematic', 1, 10),
  ('pl-david', 'bible-tea', 'David''s Crown', 'The throne, the rooftop, the son who wanted him dead.', 'thematic', 1, 11),
  ('pl-elijah', 'bible-tea', 'Fire on the Mountain', 'Solomon''s gold, then Elijah and the prophets of Baal.', 'thematic', 1, 12),
  ('pl-kings', 'bible-tea', 'The Kingdom Burns', 'Coups, leprosy, a lost book, Jerusalem on fire.', 'thematic', 1, 13),
  ('pl-empire', 'bible-tea', 'Empire Games', 'Lions, a hidden queen, a prophet who ran from a city.', 'thematic', 1, 14),
  ('pl-psalms', 'bible-tea', 'Songs After Midnight', 'The psalms you only say when the house is quiet.', 'thematic', 1, 15),
  ('pl-ashes', 'bible-tea', 'Wisdom in the Ashes', 'Job in the dirt. Proverbs across the table.', 'thematic', 1, 16),
  ('pl-late-prophets', 'bible-tea', 'The Last Voices', 'Clay, dry bones, a prophet who married a prostitute.', 'thematic', 1, 17),
  ('pl-christmas', 'bible-tea', 'Born in the Dark', 'Angels, a manger, a king who wanted the baby dead.', 'thematic', 1, 18),
  ('pl-miracles', 'bible-tea', 'He Doesn''t Stay Dead', 'Storms, lepers, 5,000 fed, a man four days in the tomb.', 'thematic', 1, 19),
  ('pl-parables', 'bible-tea', 'The Things He Said', 'The stories that flipped the room. Samaritans, sons, and a narrow door.', 'thematic', 1, 20),
  ('pl-among', 'bible-tea', 'Among the People', 'Disciples, Pharisees, a woman at a well. The ministry that would not sit still.', 'thematic', 1, 21),
  ('pl-passion', 'bible-tea', 'The Longest Week', 'A deal, a garden, a cross, an empty tomb.', 'thematic', 1, 22),
  ('pl-acts', 'bible-tea', 'Church on Fire', 'Pentecost to the first graves. The church starts loud.', 'thematic', 1, 23),
  ('pl-paul', 'bible-tea', 'To the Ends of the Earth', 'Riots, shipwrecks, house arrest. Paul will not shut up.', 'thematic', 1, 24),
  ('pl-letters', 'bible-tea', 'Ink & Prison', 'Letters from the road and the cell.', 'thematic', 1, 25),
  ('pl-end-times', 'bible-tea', 'After the Last Page', 'Horsemen, falling cities, a new earth.', 'thematic', 1, 26);

UPDATE playlists SET is_featured = 0 WHERE app_id = 'bible-tea'
  AND id NOT IN (
    'pl-origins','pl-abraham','pl-brothers','pl-exodus','pl-holy-ground','pl-wilderness',
    'pl-last-words','pl-joshua','pl-judges','pl-samuel','pl-david','pl-elijah','pl-kings',
    'pl-empire','pl-psalms','pl-ashes','pl-late-prophets','pl-christmas','pl-miracles',
    'pl-parables','pl-among','pl-passion','pl-acts','pl-paul','pl-letters','pl-end-times'
  );

UPDATE playlists SET is_featured = 1, sort_order = CASE id
  WHEN 'pl-origins' THEN 1 WHEN 'pl-abraham' THEN 2 WHEN 'pl-brothers' THEN 3
  WHEN 'pl-exodus' THEN 4 WHEN 'pl-holy-ground' THEN 5 WHEN 'pl-wilderness' THEN 6
  WHEN 'pl-last-words' THEN 7 WHEN 'pl-joshua' THEN 8 WHEN 'pl-judges' THEN 9
  WHEN 'pl-samuel' THEN 10 WHEN 'pl-david' THEN 11 WHEN 'pl-elijah' THEN 12
  WHEN 'pl-kings' THEN 13 WHEN 'pl-empire' THEN 14 WHEN 'pl-psalms' THEN 15
  WHEN 'pl-ashes' THEN 16 WHEN 'pl-late-prophets' THEN 17 WHEN 'pl-christmas' THEN 18
  WHEN 'pl-miracles' THEN 19 WHEN 'pl-parables' THEN 20 WHEN 'pl-among' THEN 21
  WHEN 'pl-passion' THEN 22 WHEN 'pl-acts' THEN 23 WHEN 'pl-paul' THEN 24
  WHEN 'pl-letters' THEN 25 WHEN 'pl-end-times' THEN 26 ELSE sort_order END
WHERE app_id = 'bible-tea' AND id IN (
  'pl-origins','pl-abraham','pl-brothers','pl-exodus','pl-holy-ground','pl-wilderness',
  'pl-last-words','pl-joshua','pl-judges','pl-samuel','pl-david','pl-elijah','pl-kings',
  'pl-empire','pl-psalms','pl-ashes','pl-late-prophets','pl-christmas','pl-miracles',
  'pl-parables','pl-among','pl-passion','pl-acts','pl-paul','pl-letters','pl-end-times'
);

UPDATE playlists SET name = 'Origin Stories', description = 'The first blood, the first flood, the first tower. How it all started.' WHERE id = 'pl-origins';
UPDATE playlists SET name = 'Abraham''s Deal', description = 'A man lies, waits, and almost kills his son because a voice told him to.' WHERE id = 'pl-abraham';
UPDATE playlists SET name = 'Brothers & Blood', description = 'Jacob steals a blessing. Joseph gets sold. Family dinner, biblical edition.' WHERE id = 'pl-brothers';
UPDATE playlists SET name = 'The Great Escape', description = 'Slavery, plagues, a sea that splits. The original action movie.' WHERE id = 'pl-exodus';
UPDATE playlists SET name = 'Holy Ground', description = 'Priests, feasts, and the rules that were supposed to make a people different.' WHERE id = 'pl-holy-ground';
UPDATE playlists SET name = 'Forty Years Lost', description = 'Snakes, spies, a talking donkey, and a nation that will not stop complaining.' WHERE id = 'pl-wilderness';
UPDATE playlists SET name = 'Moses'' Last Words', description = 'Before he dies in sight of the land: choose life, or don''t.' WHERE id = 'pl-last-words';
UPDATE playlists SET name = 'Take the Land', description = 'Jordan, Jericho, the sun stands still. Conquest with no clean hands.' WHERE id = 'pl-joshua';
UPDATE playlists SET name = 'No King. No Rules.', description = 'Tent pegs, reckless vows, Samson. Everyone did what they wanted.' WHERE id = 'pl-judges';
UPDATE playlists SET name = 'Before the Crown', description = 'A boy, a giant, a jealous king, and a witch at Endor.' WHERE id = 'pl-samuel';
UPDATE playlists SET name = 'David''s Crown', description = 'The throne, the rooftop, the son who wanted him dead.' WHERE id = 'pl-david';
UPDATE playlists SET name = 'Fire on the Mountain', description = 'Solomon''s gold, then Elijah and the prophets of Baal.' WHERE id = 'pl-elijah';
UPDATE playlists SET name = 'The Kingdom Burns', description = 'Coups, leprosy, a lost book, Jerusalem on fire.' WHERE id = 'pl-kings';
UPDATE playlists SET name = 'Empire Games', description = 'Lions, a hidden queen, a prophet who ran from a city.' WHERE id = 'pl-empire';
UPDATE playlists SET name = 'Songs After Midnight', description = 'The psalms you only say when the house is quiet.' WHERE id = 'pl-psalms';
UPDATE playlists SET name = 'Wisdom in the Ashes', description = 'Job in the dirt. Proverbs across the table.' WHERE id = 'pl-ashes';
UPDATE playlists SET name = 'The Last Voices', description = 'Clay, dry bones, a prophet who married a prostitute.' WHERE id = 'pl-late-prophets';
UPDATE playlists SET name = 'Born in the Dark', description = 'Angels, a manger, a king who wanted the baby dead.' WHERE id = 'pl-christmas';
UPDATE playlists SET name = 'He Doesn''t Stay Dead', description = 'Storms, lepers, 5,000 fed, a man four days in the tomb.' WHERE id = 'pl-miracles';
UPDATE playlists SET name = 'The Things He Said', description = 'The stories that flipped the room. Samaritans, sons, and a narrow door.' WHERE id = 'pl-parables';
UPDATE playlists SET name = 'Among the People', description = 'Disciples, Pharisees, a woman at a well. The ministry that would not sit still.' WHERE id = 'pl-among';
UPDATE playlists SET name = 'The Longest Week', description = 'A deal, a garden, a cross, an empty tomb.' WHERE id = 'pl-passion';
UPDATE playlists SET name = 'Church on Fire', description = 'Pentecost to the first graves. The church starts loud.' WHERE id = 'pl-acts';
UPDATE playlists SET name = 'To the Ends of the Earth', description = 'Riots, shipwrecks, house arrest. Paul will not shut up.' WHERE id = 'pl-paul';
UPDATE playlists SET name = 'Ink & Prison', description = 'Letters from the road and the cell.' WHERE id = 'pl-letters';
UPDATE playlists SET name = 'After the Last Page', description = 'Horsemen, falling cities, a new earth.' WHERE id = 'pl-end-times';

INSERT INTO playlist_stories (playlist_id, story_id, sort_order) VALUES
  ('pl-origins', 'st-creation', 1),
  ('pl-origins', 'st-adam-eve', 2),
  ('pl-origins', 'st-cain-abel', 3),
  ('pl-origins', 'st-noah', 4),
  ('pl-origins', 'st-babel', 5),
  ('pl-abraham', 'st-abraham-call', 1),
  ('pl-abraham', 'st-abe-sister-lie', 2),
  ('pl-abraham', 'st-same-lie', 3),
  ('pl-abraham', 'st-promise-son', 4),
  ('pl-abraham', 'st-tired-waiting', 5),
  ('pl-abraham', 'st-sodom', 6),
  ('pl-abraham', 'st-lots-escape', 7),
  ('pl-abraham', 'st-birth-isaac', 8),
  ('pl-abraham', 'st-abraham-isaac', 9),
  ('pl-abraham', 'st-isaac-rebekah', 10),
  ('pl-brothers', 'st-jacob-esau', 1),
  ('pl-brothers', 'st-jacobs-ladder', 2),
  ('pl-brothers', 'st-jacob-rachel', 3),
  ('pl-brothers', 'st-jacob-wrestles', 4),
  ('pl-brothers', 'st-joseph-brothers', 5),
  ('pl-brothers', 'st-joseph-egypt', 6),
  ('pl-brothers', 'st-joseph-forgives', 7),
  ('pl-brothers', 'st-jacob-egypt', 8),
  ('pl-exodus', 'st-baby-moses', 1),
  ('pl-exodus', 'st-burning-bush', 2),
  ('pl-exodus', 'st-ten-plagues', 3),
  ('pl-exodus', 'st-red-sea', 4),
  ('pl-exodus', 'st-bread-heaven', 5),
  ('pl-exodus', 'st-ten-commandments', 6),
  ('pl-exodus', 'st-golden-calf', 7),
  ('pl-exodus', 'st-second-chance', 8),
  ('pl-exodus', 'st-gods-tent', 9),
  ('pl-exodus', 'st-wandering', 10),
  ('pl-exodus', 'st-moses-final', 11),
  ('pl-holy-ground', 'st-first-priests', 1),
  ('pl-holy-ground', 'st-offerings', 2),
  ('pl-holy-ground', 'st-clean-unclean', 3),
  ('pl-holy-ground', 'st-atonement', 4),
  ('pl-holy-ground', 'st-holiness', 5),
  ('pl-holy-ground', 'st-feasts', 6),
  ('pl-holy-ground', 'st-sabbath-jubilee-and-justice', 7),
  ('pl-wilderness', 'st-organizing-the-camp', 1),
  ('pl-wilderness', 'st-camp-rules-and-the-cloud', 2),
  ('pl-wilderness', 'st-complaining-craving-and-chaos', 3),
  ('pl-wilderness', 'st-12-spies-and-a-40-year-detour', 4),
  ('pl-wilderness', 'st-rebellion-and-the-earth-opens', 5),
  ('pl-wilderness', 'st-snakes-water-and-the-long-road', 6),
  ('pl-wilderness', 'st-a-new-census-a-new-start', 7),
  ('pl-wilderness', 'st-make-your-promises-count', 8),
  ('pl-wilderness', 'st-a-talking-donkey-and-a-hired-prophet', 9),
  ('pl-wilderness', 'st-when-curses-wont-stick', 10),
  ('pl-wilderness', 'st-the-battle-against-midian', 11),
  ('pl-wilderness', 'st-dont-get-comfortable-too-early', 12),
  ('pl-last-words', 'st-what-kind-of-leaders-god-wants', 1),
  ('pl-last-words', 'st-rules-for-war', 2),
  ('pl-last-words', 'st-law-for-messy-lives', 3),
  ('pl-last-words', 'st-community-standards', 4),
  ('pl-last-words', 'st-one-god-one-place', 5),
  ('pl-last-words', 'st-what-god-really-wants', 6),
  ('pl-last-words', 'st-dont-let-success-ruin-you', 7),
  ('pl-last-words', 'st-remember-where-you-started', 8),
  ('pl-last-words', 'st-cancel-debts-set-people-free', 9),
  ('pl-last-words', 'st-the-ultimate-choice', 10),
  ('pl-last-words', 'st-cities-of-refuge', 11),
  ('pl-last-words', 'st-setting-boundaries', 12),
  ('pl-last-words', 'st-fair-play-and-fair-trade', 13),
  ('pl-last-words', 'st-moses-farewell-address', 14),
  ('pl-last-words', 'st-choose-life-or-death', 15),
  ('pl-last-words', 'st-blessings-and-curses', 16),
  ('pl-last-words', 'st-the-warning-song', 17),
  ('pl-joshua', 'st-joshua-takes-command', 1),
  ('pl-joshua', 'st-crossing-the-jordan', 2),
  ('pl-joshua', 'st-jericho', 3),
  ('pl-joshua', 'st-achans-hidden-sin', 4),
  ('pl-joshua', 'st-the-gibeonite-trick', 5),
  ('pl-joshua', 'st-conquering-the-land', 6),
  ('pl-joshua', 'st-caleb-claims-his-mountain', 7),
  ('pl-joshua', 'st-claim-your-inheritance', 8),
  ('pl-joshua', 'st-safe-cities-sacred-spaces', 9),
  ('pl-joshua', 'st-the-altar-that-almost-started-a-war', 10),
  ('pl-joshua', 'st-joshuas-final-challenge', 11),
  ('pl-judges', 'st-the-cycle-of-disobedience', 1),
  ('pl-judges', 'st-deborah-and-jael', 2),
  ('pl-judges', 'st-gideon-vs-the-midianites', 3),
  ('pl-judges', 'st-when-victory-goes-to-your-head', 4),
  ('pl-judges', 'st-the-bramble-king', 5),
  ('pl-judges', 'st-jephthahs-reckless-vow', 6),
  ('pl-judges', 'st-samson', 7),
  ('pl-judges', 'st-everyone-did-what-they-wanted', 8),
  ('pl-judges', 'st-homemade-religion', 9),
  ('pl-judges', 'st-ruth', 10),
  ('pl-judges', 'st-ruth-and-boaz', 11),
  ('pl-samuel', 'st-hannahs-prayer', 1),
  ('pl-samuel', 'st-samuel-anoints-saul', 2),
  ('pl-samuel', 'st-sauls-downfall', 3),
  ('pl-samuel', 'st-samuel-anoints-david', 4),
  ('pl-samuel', 'st-david-goliath', 5),
  ('pl-samuel', 'st-david-and-jonathan', 6),
  ('pl-samuel', 'st-david-spares-saul', 7),
  ('pl-samuel', 'st-the-witch-of-endor', 8),
  ('pl-david', 'st-sauls-last-stand', 1),
  ('pl-david', 'st-two-kings-two-armies', 2),
  ('pl-david', 'st-david-king', 3),
  ('pl-david', 'st-david-dances-before-the-ark', 4),
  ('pl-david', 'st-gods-promise-to-david', 5),
  ('pl-david', 'st-kindness-to-mephibosheth', 6),
  ('pl-david', 'st-david-bathsheba', 7),
  ('pl-david', 'st-absaloms-rise', 8),
  ('pl-david', 'st-absaloms-rebellion', 9),
  ('pl-david', 'st-a-fathers-worst-battle', 10),
  ('pl-david', 'st-davids-broken-return', 11),
  ('pl-david', 'st-davids-last-battles', 12),
  ('pl-david', 'st-davids-final-mistake', 13),
  ('pl-elijah', 'st-solomon', 1),
  ('pl-elijah', 'st-solomon-builds-the-temple', 2),
  ('pl-elijah', 'st-solomons-temple-dedication', 3),
  ('pl-elijah', 'st-queen-of-sheba', 4),
  ('pl-elijah', 'st-solomons-downfall', 5),
  ('pl-elijah', 'st-the-kingdom-splits', 6),
  ('pl-elijah', 'st-elijah-fed-by-ravens', 7),
  ('pl-elijah', 'st-elijah-and-the-widow', 8),
  ('pl-elijah', 'st-elijah-on-mount-carmel', 9),
  ('pl-elijah', 'st-elijah-runs-from-jezebel', 10),
  ('pl-elijah', 'st-naboths-vineyard', 11),
  ('pl-elijah', 'st-elijah-taken-to-heaven', 12),
  ('pl-kings', 'st-kings-who-copied-the-worst', 1),
  ('pl-kings', 'st-decay-coups-and-leprosy', 2),
  ('pl-kings', 'st-one-angel-one-army-destroyed', 3),
  ('pl-kings', 'st-hezekiah-vs-the-empire', 4),
  ('pl-kings', 'st-hezekiahs-revival', 5),
  ('pl-kings', 'st-hezekiahs-extra-years', 6),
  ('pl-kings', 'st-manasseh-hits-reverse', 7),
  ('pl-kings', 'st-josiah-finds-the-lost-book', 8),
  ('pl-kings', 'st-josiahs-last-battle', 9),
  ('pl-kings', 'st-the-northern-kingdom-falls', 10),
  ('pl-kings', 'st-jerusalem-burns', 11),
  ('pl-empire', 'st-nebuchadnezzars-dream', 1),
  ('pl-empire', 'st-the-fiery-furnace', 2),
  ('pl-empire', 'st-daniel-lions', 3),
  ('pl-empire', 'st-the-writing-on-the-wall', 4),
  ('pl-empire', 'st-daniels-visions', 5),
  ('pl-empire', 'st-esther-becomes-queen', 6),
  ('pl-empire', 'st-hamans-plot', 7),
  ('pl-empire', 'st-esthers-banquet', 8),
  ('pl-empire', 'st-esther', 9),
  ('pl-empire', 'st-jonah', 10),
  ('pl-empire', 'st-jonahs-anger', 11),
  ('pl-psalms', 'st-david-writes-psalm-23', 1),
  ('pl-psalms', 'st-songs-in-the-night', 2),
  ('pl-psalms', 'st-psalm-51-a-broken-king', 3),
  ('pl-psalms', 'st-psalm-91-gods-protection', 4),
  ('pl-psalms', 'st-psalm-139-fully-known', 5),
  ('pl-psalms', 'st-psalm-150-everything-praise', 6),
  ('pl-ashes', 'st-jobs-suffering', 1),
  ('pl-ashes', 'st-jobs-friends-speak', 2),
  ('pl-ashes', 'st-god-answers-job', 3),
  ('pl-ashes', 'st-job-restored', 4),
  ('pl-ashes', 'st-solomons-proverbs', 5),
  ('pl-ashes', 'st-the-wise-and-the-foolish', 6),
  ('pl-ashes', 'st-the-proverbs-31-woman', 7),
  ('pl-late-prophets', 'st-isaiahs-vision', 1),
  ('pl-late-prophets', 'st-isaiahs-call', 2),
  ('pl-late-prophets', 'st-immanuel-prophecy', 3),
  ('pl-late-prophets', 'st-new-heavens-new-earth-isaiah', 4),
  ('pl-late-prophets', 'st-jeremiah-the-weeping-prophet', 5),
  ('pl-late-prophets', 'st-the-potters-clay', 6),
  ('pl-late-prophets', 'st-jeremiah-in-the-cistern', 7),
  ('pl-late-prophets', 'st-the-new-covenant', 8),
  ('pl-late-prophets', 'st-ezekiels-call-and-the-wheel', 9),
  ('pl-late-prophets', 'st-valley-of-dry-bones', 10),
  ('pl-late-prophets', 'st-the-restored-temple', 11),
  ('pl-late-prophets', 'st-hosea-and-gomer', 12),
  ('pl-late-prophets', 'st-israels-unfaithfulness', 13),
  ('pl-late-prophets', 'st-gods-love-wins', 14),
  ('pl-christmas', 'st-angel-visits-zechariah', 1),
  ('pl-christmas', 'st-angel-visits-mary', 2),
  ('pl-christmas', 'st-birth-of-john-the-baptist', 3),
  ('pl-christmas', 'st-birth-jesus', 4),
  ('pl-christmas', 'st-simeon-and-anna', 5),
  ('pl-christmas', 'st-the-wise-men', 6),
  ('pl-christmas', 'st-flight-to-egypt', 7),
  ('pl-christmas', 'st-boy-jesus-at-the-temple', 8),
  ('pl-miracles', 'st-baptism', 1),
  ('pl-miracles', 'st-40-days-in-the-desert', 2),
  ('pl-miracles', 'st-first-miracles', 3),
  ('pl-miracles', 'st-the-miraculous-catch', 4),
  ('pl-miracles', 'st-casting-out-an-evil-spirit', 5),
  ('pl-miracles', 'st-peters-mother-in-law-healed', 6),
  ('pl-miracles', 'st-touching-the-leper', 7),
  ('pl-miracles', 'st-through-the-roof', 8),
  ('pl-miracles', 'st-the-centurions-faith', 9),
  ('pl-miracles', 'st-jesus-stops-a-storm', 10),
  ('pl-miracles', 'st-legion-and-the-pigs', 11),
  ('pl-miracles', 'st-jairus-daughter-and-the-bleeding-woman', 12),
  ('pl-miracles', 'st-the-widows-son-lives-again', 13),
  ('pl-miracles', 'st-feeds-5000', 14),
  ('pl-miracles', 'st-walks-water', 15),
  ('pl-miracles', 'st-deaf-ears-opened', 16),
  ('pl-miracles', 'st-feeding-4000', 17),
  ('pl-miracles', 'st-the-boy-with-a-demon', 18),
  ('pl-miracles', 'st-the-fish-with-a-coin', 19),
  ('pl-miracles', 'st-healing-at-the-pool', 20),
  ('pl-miracles', 'st-healing-the-officials-son', 21),
  ('pl-miracles', 'st-born-blind-now-sees', 22),
  ('pl-miracles', 'st-lazarus-lives-again', 23),
  ('pl-parables', 'st-good-samaritan', 1),
  ('pl-parables', 'st-prodigal-son', 2),
  ('pl-parables', 'st-the-wedding-feast-parables', 3),
  ('pl-parables', 'st-the-narrow-door', 4),
  ('pl-parables', 'st-counting-the-cost', 5),
  ('pl-parables', 'st-the-shrewd-manager', 6),
  ('pl-parables', 'st-the-rich-man-and-lazarus', 7),
  ('pl-parables', 'st-the-good-shepherd', 8),
  ('pl-parables', 'st-teaching-them-to-pray', 9),
  ('pl-parables', 'st-the-greatest-commandment', 10),
  ('pl-parables', 'st-caesars-coin', 11),
  ('pl-parables', 'st-faith-figs-and-loaded-questions', 12),
  ('pl-parables', 'st-marriage-and-the-afterlife', 13),
  ('pl-parables', 'st-whose-son-is-the-messiah', 14),
  ('pl-parables', 'st-signs-of-the-end', 15),
  ('pl-among', 'st-john-the-baptist-preaches', 1),
  ('pl-among', 'st-john-declares-the-lamb', 2),
  ('pl-among', 'st-meeting-the-first-disciples', 3),
  ('pl-among', 'st-matthew-leaves-everything', 4),
  ('pl-among', 'st-picking-the-twelve', 5),
  ('pl-among', 'st-nicodemus-comes-at-night', 6),
  ('pl-among', 'st-the-woman-at-the-well', 7),
  ('pl-among', 'st-jesus-flips-tables', 8),
  ('pl-among', 'st-the-sabbath-showdowns', 9),
  ('pl-among', 'st-demons-and-accusations', 10),
  ('pl-among', 'st-john-the-baptist-beheaded', 11),
  ('pl-among', 'st-john-the-baptists-last-words', 12),
  ('pl-among', 'st-the-purity-debate', 13),
  ('pl-among', 'st-a-mothers-desperate-faith', 14),
  ('pl-among', 'st-peters-big-confession', 15),
  ('pl-among', 'st-the-transfiguration', 16),
  ('pl-among', 'st-jesus-predicts-his-death', 17),
  ('pl-among', 'st-the-cursed-fig-tree', 18),
  ('pl-among', 'st-mary-and-martha', 19),
  ('pl-among', 'st-sending-out-72', 20),
  ('pl-among', 'st-casting-out-demons-and-taking-heat', 21),
  ('pl-among', 'st-calling-out-the-pharisees', 22),
  ('pl-among', 'st-bread-of-life', 23),
  ('pl-among', 'st-the-festival-showdown', 24),
  ('pl-among', 'st-go-ahead-throw-a-stone', 25),
  ('pl-among', 'st-zacchaeus-climbs-a-tree', 26),
  ('pl-passion', 'st-anointed-at-bethany', 1),
  ('pl-passion', 'st-the-plot-against-jesus', 2),
  ('pl-passion', 'st-judas-makes-a-deal', 3),
  ('pl-passion', 'st-palm-sunday', 4),
  ('pl-passion', 'st-last-supper', 5),
  ('pl-passion', 'st-gethsemane', 6),
  ('pl-passion', 'st-arrested-in-the-garden', 7),
  ('pl-passion', 'st-before-the-sanhedrin', 8),
  ('pl-passion', 'st-peters-three-denials', 9),
  ('pl-passion', 'st-jesus-before-pilate', 10),
  ('pl-passion', 'st-crucifixion', 11),
  ('pl-passion', 'st-buried-in-a-borrowed-tomb', 12),
  ('pl-passion', 'st-resurrection', 13),
  ('pl-passion', 'st-the-road-to-emmaus', 14),
  ('pl-passion', 'st-doubting-thomas', 15),
  ('pl-passion', 'st-the-great-commission', 16),
  ('pl-acts', 'st-the-ascension', 1),
  ('pl-acts', 'st-pentecost', 2),
  ('pl-acts', 'st-the-beautiful-gate-miracle', 3),
  ('pl-acts', 'st-ananias-and-sapphira', 4),
  ('pl-acts', 'st-stephen-the-first-martyr', 5),
  ('pl-acts', 'st-the-church-scatters', 6),
  ('pl-acts', 'st-saul-meets-jesus', 7),
  ('pl-acts', 'st-peters-miracles', 8),
  ('pl-acts', 'st-cornelius-and-the-vision', 9),
  ('pl-acts', 'st-the-antioch-church', 10),
  ('pl-acts', 'st-james-killed-peter-escapes', 11),
  ('pl-paul', 'st-pauls-first-journey', 1),
  ('pl-paul', 'st-the-jerusalem-council', 2),
  ('pl-paul', 'st-earthquake-at-philippi', 3),
  ('pl-paul', 'st-thessalonica-riot-and-berea', 4),
  ('pl-paul', 'st-athens-the-unknown-god', 5),
  ('pl-paul', 'st-riot-in-ephesus', 6),
  ('pl-paul', 'st-eutychus-falls-out-a-window', 7),
  ('pl-paul', 'st-farewell-at-miletus', 8),
  ('pl-paul', 'st-arrested-at-the-temple', 9),
  ('pl-paul', 'st-trials-before-governors', 10),
  ('pl-paul', 'st-shipwreck-and-malta', 11),
  ('pl-paul', 'st-paul-under-house-arrest', 12),
  ('pl-letters', 'st-love-is', 1),
  ('pl-letters', 'st-armor-of-god', 2),
  ('pl-letters', 'st-paul-and-timothy', 3),
  ('pl-letters', 'st-pauls-letter-to-rome', 4),
  ('pl-letters', 'st-james-writes-to-the-church', 5),
  ('pl-letters', 'st-taming-the-tongue', 6),
  ('pl-letters', 'st-faith-without-works', 7),
  ('pl-letters', 'st-peters-final-letter', 8),
  ('pl-letters', 'st-guard-the-truth', 9),
  ('pl-letters', 'st-pauls-last-letter', 10),
  ('pl-letters', 'st-finish-the-race', 11),
  ('pl-end-times', 'st-johns-exile-and-revelation', 1),
  ('pl-end-times', 'st-letters-to-seven-churches', 2),
  ('pl-end-times', 'st-the-four-horsemen', 3),
  ('pl-end-times', 'st-the-fall-of-babylon', 4),
  ('pl-end-times', 'st-the-new-heaven-and-new-earth', 5);

INSERT OR REPLACE INTO content_translations (app_id, entity_type, entity_id, locale, field, value) VALUES
  ('bible-tea', 'playlist', 'pl-origins', 'es', 'name', 'Historias de Origen'),
  ('bible-tea', 'playlist', 'pl-origins', 'es', 'description', 'La primera sangre, el primer diluvio, la primera torre.'),
  ('bible-tea', 'playlist', 'pl-abraham', 'es', 'name', 'El Trato de Abraham'),
  ('bible-tea', 'playlist', 'pl-abraham', 'es', 'description', 'Miente, espera y casi mata a su hijo porque una voz se lo pidió.'),
  ('bible-tea', 'playlist', 'pl-brothers', 'es', 'name', 'Hermanos y Sangre'),
  ('bible-tea', 'playlist', 'pl-brothers', 'es', 'description', 'Jacob roba una bendición. José es vendido.'),
  ('bible-tea', 'playlist', 'pl-exodus', 'es', 'name', 'La Gran Escapada'),
  ('bible-tea', 'playlist', 'pl-last-words', 'es', 'name', 'Las Últimas Palabras de Moisés'),
  ('bible-tea', 'playlist', 'pl-joshua', 'es', 'name', 'Tomen la Tierra'),
  ('bible-tea', 'playlist', 'pl-judges', 'es', 'name', 'Sin Rey. Sin Reglas.'),
  ('bible-tea', 'playlist', 'pl-samuel', 'es', 'name', 'Antes de la Corona'),
  ('bible-tea', 'playlist', 'pl-david', 'es', 'name', 'La Corona de David'),
  ('bible-tea', 'playlist', 'pl-elijah', 'es', 'name', 'Fuego en la Montaña'),
  ('bible-tea', 'playlist', 'pl-kings', 'es', 'name', 'El Reino Arde'),
  ('bible-tea', 'playlist', 'pl-empire', 'es', 'name', 'Juegos de Imperio'),
  ('bible-tea', 'playlist', 'pl-psalms', 'es', 'name', 'Canciones Después de Medianoche'),
  ('bible-tea', 'playlist', 'pl-ashes', 'es', 'name', 'Sabiduría en las Cenizas'),
  ('bible-tea', 'playlist', 'pl-late-prophets', 'es', 'name', 'Las Últimas Voces'),
  ('bible-tea', 'playlist', 'pl-christmas', 'es', 'name', 'Nacido en la Oscuridad'),
  ('bible-tea', 'playlist', 'pl-miracles', 'es', 'name', 'Él No Se Queda Muerto'),
  ('bible-tea', 'playlist', 'pl-parables', 'es', 'name', 'Lo Que Él Dijo'),
  ('bible-tea', 'playlist', 'pl-among', 'es', 'name', 'Entre la Gente'),
  ('bible-tea', 'playlist', 'pl-passion', 'es', 'name', 'La Semana Más Larga'),
  ('bible-tea', 'playlist', 'pl-acts', 'es', 'name', 'Iglesia en Llamas'),
  ('bible-tea', 'playlist', 'pl-paul', 'es', 'name', 'Hasta los Confines'),
  ('bible-tea', 'playlist', 'pl-letters', 'es', 'name', 'Tinta y Prisión'),
  ('bible-tea', 'playlist', 'pl-end-times', 'es', 'name', 'Después de la Última Página'),
  ('bible-tea', 'playlist', 'pl-wilderness', 'es', 'name', 'Cuarenta Años Perdidos'),
  ('bible-tea', 'playlist', 'pl-holy-ground', 'es', 'name', 'Tierra Santa');
