-- Restore bible_ref on stories. Run after ADD COLUMN. Safe to re-run.

UPDATE stories SET bible_ref = 'Genesis 1-2' WHERE id = 'st-creation';
UPDATE stories SET bible_ref = 'Genesis 2-3' WHERE id = 'st-adam-eve';
UPDATE stories SET bible_ref = 'Genesis 4' WHERE id = 'st-cain-abel';
UPDATE stories SET bible_ref = 'Genesis 6-9' WHERE id = 'st-noah';
UPDATE stories SET bible_ref = 'Genesis 11' WHERE id = 'st-babel';
UPDATE stories SET bible_ref = 'Genesis 12' WHERE id = 'st-abraham-call';
UPDATE stories SET bible_ref = 'Genesis 22' WHERE id = 'st-abraham-isaac';
UPDATE stories SET bible_ref = 'Genesis 25, 27' WHERE id = 'st-jacob-esau';
UPDATE stories SET bible_ref = 'Genesis 28' WHERE id = 'st-jacobs-ladder';
UPDATE stories SET bible_ref = 'Genesis 37' WHERE id = 'st-joseph-brothers';
UPDATE stories SET bible_ref = 'Genesis 39-41' WHERE id = 'st-joseph-egypt';
UPDATE stories SET bible_ref = 'Genesis 42-45' WHERE id = 'st-joseph-forgives';
UPDATE stories SET bible_ref = 'Exodus 2' WHERE id = 'st-baby-moses';
UPDATE stories SET bible_ref = 'Exodus 3-4' WHERE id = 'st-burning-bush';
UPDATE stories SET bible_ref = 'Exodus 7-12' WHERE id = 'st-ten-plagues';
UPDATE stories SET bible_ref = 'Exodus 14' WHERE id = 'st-red-sea';
UPDATE stories SET bible_ref = 'Exodus 19-20' WHERE id = 'st-ten-commandments';
UPDATE stories SET bible_ref = 'Exodus 32' WHERE id = 'st-golden-calf';
UPDATE stories SET bible_ref = 'Numbers 14-36' WHERE id = 'st-wandering';
UPDATE stories SET bible_ref = 'Deuteronomy 34' WHERE id = 'st-moses-final';
UPDATE stories SET bible_ref = 'Joshua 6' WHERE id = 'st-jericho';
UPDATE stories SET bible_ref = 'Judges 13-16' WHERE id = 'st-samson';
UPDATE stories SET bible_ref = 'Ruth 1-4' WHERE id = 'st-ruth';
UPDATE stories SET bible_ref = '1 Samuel 17' WHERE id = 'st-david-goliath';
UPDATE stories SET bible_ref = '2 Samuel 5' WHERE id = 'st-david-king';
UPDATE stories SET bible_ref = '2 Samuel 11-12' WHERE id = 'st-david-bathsheba';
UPDATE stories SET bible_ref = '1 Kings 3' WHERE id = 'st-solomon';
UPDATE stories SET bible_ref = 'Daniel 6' WHERE id = 'st-daniel-lions';
UPDATE stories SET bible_ref = 'Jonah 1-4' WHERE id = 'st-jonah';
UPDATE stories SET bible_ref = 'Esther 1-10' WHERE id = 'st-esther';
UPDATE stories SET bible_ref = 'Luke 2:1-20' WHERE id = 'st-birth-jesus';
UPDATE stories SET bible_ref = 'Matthew 3:13-17' WHERE id = 'st-baptism';
UPDATE stories SET bible_ref = 'John 2:1-11' WHERE id = 'st-first-miracles';
UPDATE stories SET bible_ref = 'Luke 10:25-37' WHERE id = 'st-good-samaritan';
UPDATE stories SET bible_ref = 'Luke 15' WHERE id = 'st-prodigal-son';
UPDATE stories SET bible_ref = 'Matthew 14:22-33' WHERE id = 'st-walks-water';
UPDATE stories SET bible_ref = 'Matthew 14:13-21' WHERE id = 'st-feeds-5000';
UPDATE stories SET bible_ref = 'Matthew 26:17-30' WHERE id = 'st-last-supper';
UPDATE stories SET bible_ref = 'Matthew 27:32-56' WHERE id = 'st-crucifixion';
UPDATE stories SET bible_ref = 'Matthew 28:1-10' WHERE id = 'st-resurrection';
UPDATE stories SET bible_ref = 'Genesis 12:10-20' WHERE id = 'st-abe-sister-lie';
UPDATE stories SET bible_ref = 'Genesis 20' WHERE id = 'st-same-lie';
UPDATE stories SET bible_ref = 'Genesis 15-17' WHERE id = 'st-promise-son';
UPDATE stories SET bible_ref = 'Genesis 16' WHERE id = 'st-tired-waiting';
UPDATE stories SET bible_ref = 'Genesis 18-19' WHERE id = 'st-sodom';
UPDATE stories SET bible_ref = 'Genesis 19:30-38' WHERE id = 'st-lots-escape';
UPDATE stories SET bible_ref = 'Genesis 21' WHERE id = 'st-birth-isaac';
UPDATE stories SET bible_ref = 'Genesis 24' WHERE id = 'st-isaac-rebekah';
UPDATE stories SET bible_ref = 'Genesis 29-30' WHERE id = 'st-jacob-rachel';
UPDATE stories SET bible_ref = 'Genesis 32' WHERE id = 'st-jacob-wrestles';
UPDATE stories SET bible_ref = 'Genesis 46-47' WHERE id = 'st-jacob-egypt';
UPDATE stories SET bible_ref = 'Exodus 16-17' WHERE id = 'st-bread-heaven';
UPDATE stories SET bible_ref = 'Exodus 34' WHERE id = 'st-second-chance';
UPDATE stories SET bible_ref = 'Exodus 35-40' WHERE id = 'st-gods-tent';
UPDATE stories SET bible_ref = 'Leviticus 8-10' WHERE id = 'st-first-priests';
UPDATE stories SET bible_ref = 'Leviticus 1-7' WHERE id = 'st-offerings';
UPDATE stories SET bible_ref = 'Leviticus 11-15' WHERE id = 'st-clean-unclean';
UPDATE stories SET bible_ref = 'Leviticus 16' WHERE id = 'st-atonement';
UPDATE stories SET bible_ref = 'Leviticus 19' WHERE id = 'st-holiness';
UPDATE stories SET bible_ref = 'Leviticus 23' WHERE id = 'st-feasts';
UPDATE stories SET bible_ref = 'Leviticus 25' WHERE id = 'st-sabbath-jubilee-and-justice';
UPDATE stories SET bible_ref = 'Numbers 1-4' WHERE id = 'st-organizing-the-camp';
UPDATE stories SET bible_ref = 'Numbers 5-10' WHERE id = 'st-camp-rules-and-the-cloud';
UPDATE stories SET bible_ref = 'Numbers 11' WHERE id = 'st-complaining-craving-and-chaos';
UPDATE stories SET bible_ref = 'Numbers 13-14' WHERE id = 'st-12-spies-and-a-40-year-detour';
UPDATE stories SET bible_ref = 'Numbers 16' WHERE id = 'st-rebellion-and-the-earth-opens';
UPDATE stories SET bible_ref = 'Numbers 20-21' WHERE id = 'st-snakes-water-and-the-long-road';
UPDATE stories SET bible_ref = 'Numbers 26' WHERE id = 'st-a-new-census-a-new-start';
UPDATE stories SET bible_ref = 'Numbers 30' WHERE id = 'st-make-your-promises-count';
UPDATE stories SET bible_ref = 'Numbers 22' WHERE id = 'st-a-talking-donkey-and-a-hired-prophet';
UPDATE stories SET bible_ref = 'Numbers 23-24' WHERE id = 'st-when-curses-wont-stick';
UPDATE stories SET bible_ref = 'Numbers 31' WHERE id = 'st-the-battle-against-midian';
UPDATE stories SET bible_ref = 'Numbers 32' WHERE id = 'st-dont-get-comfortable-too-early';
UPDATE stories SET bible_ref = 'Deuteronomy 17-18' WHERE id = 'st-what-kind-of-leaders-god-wants';
UPDATE stories SET bible_ref = 'Deuteronomy 20' WHERE id = 'st-rules-for-war';
UPDATE stories SET bible_ref = 'Deuteronomy 21-22' WHERE id = 'st-law-for-messy-lives';
UPDATE stories SET bible_ref = 'Deuteronomy 23-25' WHERE id = 'st-community-standards';
UPDATE stories SET bible_ref = 'Deuteronomy 12-14' WHERE id = 'st-one-god-one-place';
UPDATE stories SET bible_ref = 'Deuteronomy 10' WHERE id = 'st-what-god-really-wants';
UPDATE stories SET bible_ref = 'Deuteronomy 8' WHERE id = 'st-dont-let-success-ruin-you';
UPDATE stories SET bible_ref = 'Deuteronomy 7-9' WHERE id = 'st-remember-where-you-started';
UPDATE stories SET bible_ref = 'Deuteronomy 15' WHERE id = 'st-cancel-debts-set-people-free';
UPDATE stories SET bible_ref = 'Deuteronomy 30' WHERE id = 'st-the-ultimate-choice';
UPDATE stories SET bible_ref = 'Deuteronomy 19' WHERE id = 'st-cities-of-refuge';
UPDATE stories SET bible_ref = 'Deuteronomy 27' WHERE id = 'st-setting-boundaries';
UPDATE stories SET bible_ref = 'Deuteronomy 25' WHERE id = 'st-fair-play-and-fair-trade';
UPDATE stories SET bible_ref = 'Deuteronomy 33' WHERE id = 'st-moses-farewell-address';
UPDATE stories SET bible_ref = 'Deuteronomy 30:15-20' WHERE id = 'st-choose-life-or-death';
UPDATE stories SET bible_ref = 'Deuteronomy 28' WHERE id = 'st-blessings-and-curses';
UPDATE stories SET bible_ref = 'Deuteronomy 31-32' WHERE id = 'st-the-warning-song';
UPDATE stories SET bible_ref = 'Joshua 1-2' WHERE id = 'st-joshua-takes-command';
UPDATE stories SET bible_ref = 'Joshua 3-4' WHERE id = 'st-crossing-the-jordan';
UPDATE stories SET bible_ref = 'Joshua 7' WHERE id = 'st-achans-hidden-sin';
UPDATE stories SET bible_ref = 'Joshua 9-10' WHERE id = 'st-the-gibeonite-trick';
UPDATE stories SET bible_ref = 'Joshua 10-12' WHERE id = 'st-conquering-the-land';
UPDATE stories SET bible_ref = 'Joshua 14' WHERE id = 'st-caleb-claims-his-mountain';
UPDATE stories SET bible_ref = 'Joshua 18' WHERE id = 'st-claim-your-inheritance';
UPDATE stories SET bible_ref = 'Joshua 20-21' WHERE id = 'st-safe-cities-sacred-spaces';
UPDATE stories SET bible_ref = 'Joshua 22' WHERE id = 'st-the-altar-that-almost-started-a-war';
UPDATE stories SET bible_ref = 'Joshua 24' WHERE id = 'st-joshuas-final-challenge';
UPDATE stories SET bible_ref = 'Judges 1-3' WHERE id = 'st-the-cycle-of-disobedience';
UPDATE stories SET bible_ref = 'Judges 4-5' WHERE id = 'st-deborah-and-jael';
UPDATE stories SET bible_ref = 'Judges 6-7' WHERE id = 'st-gideon-vs-the-midianites';
UPDATE stories SET bible_ref = 'Judges 8' WHERE id = 'st-when-victory-goes-to-your-head';
UPDATE stories SET bible_ref = 'Judges 9' WHERE id = 'st-the-bramble-king';
UPDATE stories SET bible_ref = 'Judges 11' WHERE id = 'st-jephthahs-reckless-vow';
UPDATE stories SET bible_ref = 'Judges 17-21' WHERE id = 'st-everyone-did-what-they-wanted';
UPDATE stories SET bible_ref = 'Judges 17-18' WHERE id = 'st-homemade-religion';
UPDATE stories SET bible_ref = '2 Samuel 1' WHERE id = 'st-sauls-last-stand';
UPDATE stories SET bible_ref = '2 Samuel 2-4' WHERE id = 'st-two-kings-two-armies';
UPDATE stories SET bible_ref = '2 Samuel 6' WHERE id = 'st-david-dances-before-the-ark';
UPDATE stories SET bible_ref = '2 Samuel 7' WHERE id = 'st-gods-promise-to-david';
UPDATE stories SET bible_ref = '2 Samuel 9' WHERE id = 'st-kindness-to-mephibosheth';
UPDATE stories SET bible_ref = '2 Samuel 13-14' WHERE id = 'st-absaloms-rise';
UPDATE stories SET bible_ref = '2 Samuel 15-17' WHERE id = 'st-absaloms-rebellion';
UPDATE stories SET bible_ref = '2 Samuel 18' WHERE id = 'st-a-fathers-worst-battle';
UPDATE stories SET bible_ref = '2 Samuel 19-20' WHERE id = 'st-davids-broken-return';
UPDATE stories SET bible_ref = '2 Samuel 21-23' WHERE id = 'st-davids-last-battles';
UPDATE stories SET bible_ref = '2 Samuel 24' WHERE id = 'st-davids-final-mistake';
UPDATE stories SET bible_ref = '1 Kings 18' WHERE id = 'st-elijah-on-mount-carmel';
UPDATE stories SET bible_ref = '1 Kings 12' WHERE id = 'st-the-kingdom-splits';
UPDATE stories SET bible_ref = '1-2 Kings, various passages' WHERE id = 'st-kings-who-copied-the-worst';
UPDATE stories SET bible_ref = '2 Kings various' WHERE id = 'st-decay-coups-and-leprosy';
UPDATE stories SET bible_ref = '2 Kings 21' WHERE id = 'st-manasseh-hits-reverse';
UPDATE stories SET bible_ref = '2 Kings 22-23' WHERE id = 'st-josiah-finds-the-lost-book';
UPDATE stories SET bible_ref = '2 Chronicles 35' WHERE id = 'st-josiahs-last-battle';
UPDATE stories SET bible_ref = '2 Kings 20' WHERE id = 'st-hezekiahs-extra-years';
UPDATE stories SET bible_ref = '2 Kings 19' WHERE id = 'st-one-angel-one-army-destroyed';
UPDATE stories SET bible_ref = '2 Chronicles 32' WHERE id = 'st-hezekiah-vs-the-empire';
UPDATE stories SET bible_ref = '2 Kings 17' WHERE id = 'st-the-northern-kingdom-falls';
UPDATE stories SET bible_ref = '2 Kings 25' WHERE id = 'st-jerusalem-burns';
UPDATE stories SET bible_ref = 'Luke 1:5-25' WHERE id = 'st-angel-visits-zechariah';
UPDATE stories SET bible_ref = 'Luke 1:26-38' WHERE id = 'st-angel-visits-mary';
UPDATE stories SET bible_ref = 'Luke 1:57-80' WHERE id = 'st-birth-of-john-the-baptist';
UPDATE stories SET bible_ref = 'Luke 2:22-40' WHERE id = 'st-simeon-and-anna';
UPDATE stories SET bible_ref = 'Matthew 2:1-12' WHERE id = 'st-the-wise-men';
UPDATE stories SET bible_ref = 'Matthew 2:13-23' WHERE id = 'st-flight-to-egypt';
UPDATE stories SET bible_ref = 'Luke 2:41-52' WHERE id = 'st-boy-jesus-at-the-temple';
UPDATE stories SET bible_ref = 'Matthew 3:1-12' WHERE id = 'st-john-the-baptist-preaches';
UPDATE stories SET bible_ref = 'John 1:29-34' WHERE id = 'st-john-declares-the-lamb';
UPDATE stories SET bible_ref = 'Matthew 4:1-11' WHERE id = 'st-40-days-in-the-desert';
UPDATE stories SET bible_ref = 'John 1:35-51' WHERE id = 'st-meeting-the-first-disciples';
UPDATE stories SET bible_ref = 'John 3:1-21' WHERE id = 'st-nicodemus-comes-at-night';
UPDATE stories SET bible_ref = 'John 2:13-25' WHERE id = 'st-jesus-flips-tables';
UPDATE stories SET bible_ref = 'John 3:22-36' WHERE id = 'st-john-the-baptists-last-words';
UPDATE stories SET bible_ref = 'John 5' WHERE id = 'st-healing-at-the-pool';
UPDATE stories SET bible_ref = 'Luke 5:1-11' WHERE id = 'st-the-miraculous-catch';
UPDATE stories SET bible_ref = 'Mark 1:21-28' WHERE id = 'st-casting-out-an-evil-spirit';
UPDATE stories SET bible_ref = 'Mark 1:29-34' WHERE id = 'st-peters-mother-in-law-healed';
UPDATE stories SET bible_ref = 'Mark 1:40-45' WHERE id = 'st-touching-the-leper';
UPDATE stories SET bible_ref = 'Mark 2:1-12' WHERE id = 'st-through-the-roof';
UPDATE stories SET bible_ref = 'Matthew 9:9-13' WHERE id = 'st-matthew-leaves-everything';
UPDATE stories SET bible_ref = 'Matthew 12:1-14' WHERE id = 'st-the-sabbath-showdowns';
UPDATE stories SET bible_ref = 'Luke 6:12-49' WHERE id = 'st-picking-the-twelve';
UPDATE stories SET bible_ref = 'Matthew 8:5-13' WHERE id = 'st-the-centurions-faith';
UPDATE stories SET bible_ref = 'Luke 7:11-17' WHERE id = 'st-the-widows-son-lives-again';
UPDATE stories SET bible_ref = 'Mark 7:31-37' WHERE id = 'st-deaf-ears-opened';
UPDATE stories SET bible_ref = 'Mark 4:35-41' WHERE id = 'st-jesus-stops-a-storm';
UPDATE stories SET bible_ref = 'Mark 5:1-20' WHERE id = 'st-legion-and-the-pigs';
UPDATE stories SET bible_ref = 'Mark 5:21-43' WHERE id = 'st-jairus-daughter-and-the-bleeding-woman';
UPDATE stories SET bible_ref = 'John 4:43-54' WHERE id = 'st-healing-the-officials-son';
UPDATE stories SET bible_ref = 'Matthew 12:22-37' WHERE id = 'st-demons-and-accusations';
UPDATE stories SET bible_ref = 'Matthew 14:1-12' WHERE id = 'st-john-the-baptist-beheaded';
UPDATE stories SET bible_ref = 'Matthew 15:32-39' WHERE id = 'st-feeding-4000';
UPDATE stories SET bible_ref = 'John 6:22-71' WHERE id = 'st-bread-of-life';
UPDATE stories SET bible_ref = 'Mark 7:1-23' WHERE id = 'st-the-purity-debate';
UPDATE stories SET bible_ref = 'Mark 7:24-30' WHERE id = 'st-a-mothers-desperate-faith';
UPDATE stories SET bible_ref = 'Matthew 16:13-28' WHERE id = 'st-peters-big-confession';
UPDATE stories SET bible_ref = 'Matthew 17:1-13' WHERE id = 'st-the-transfiguration';
UPDATE stories SET bible_ref = 'Matthew 17:14-21' WHERE id = 'st-the-boy-with-a-demon';
UPDATE stories SET bible_ref = 'Matthew 20:17-19' WHERE id = 'st-jesus-predicts-his-death';
UPDATE stories SET bible_ref = 'Matthew 17:24-27' WHERE id = 'st-the-fish-with-a-coin';
UPDATE stories SET bible_ref = 'John 7' WHERE id = 'st-the-festival-showdown';
UPDATE stories SET bible_ref = 'John 9' WHERE id = 'st-born-blind-now-sees';
UPDATE stories SET bible_ref = 'John 10' WHERE id = 'st-the-good-shepherd';
UPDATE stories SET bible_ref = 'Luke 10:1-24' WHERE id = 'st-sending-out-72';
UPDATE stories SET bible_ref = 'Luke 10:38-42' WHERE id = 'st-mary-and-martha';
UPDATE stories SET bible_ref = 'Luke 11:1-13' WHERE id = 'st-teaching-them-to-pray';
UPDATE stories SET bible_ref = 'Luke 11:14-28' WHERE id = 'st-casting-out-demons-and-taking-heat';
UPDATE stories SET bible_ref = 'Luke 11:37-54' WHERE id = 'st-calling-out-the-pharisees';
UPDATE stories SET bible_ref = 'John 4:1-42' WHERE id = 'st-the-woman-at-the-well';
UPDATE stories SET bible_ref = 'John 11:1-44' WHERE id = 'st-lazarus-lives-again';
UPDATE stories SET bible_ref = 'John 8:1-11' WHERE id = 'st-go-ahead-throw-a-stone';
UPDATE stories SET bible_ref = 'Luke 14:1-24' WHERE id = 'st-the-wedding-feast-parables';
UPDATE stories SET bible_ref = 'Luke 13:22-30' WHERE id = 'st-the-narrow-door';
UPDATE stories SET bible_ref = 'Luke 14:25-35' WHERE id = 'st-counting-the-cost';
UPDATE stories SET bible_ref = 'Luke 16:1-15' WHERE id = 'st-the-shrewd-manager';
UPDATE stories SET bible_ref = 'Luke 16:19-31' WHERE id = 'st-the-rich-man-and-lazarus';
UPDATE stories SET bible_ref = 'Luke 19:1-10' WHERE id = 'st-zacchaeus-climbs-a-tree';
UPDATE stories SET bible_ref = 'Mark 11:12-25' WHERE id = 'st-the-cursed-fig-tree';
UPDATE stories SET bible_ref = 'Matthew 21:1-11' WHERE id = 'st-palm-sunday';
UPDATE stories SET bible_ref = 'Matthew 22:15-22' WHERE id = 'st-caesars-coin';
UPDATE stories SET bible_ref = 'Matthew 21-22' WHERE id = 'st-faith-figs-and-loaded-questions';
UPDATE stories SET bible_ref = 'Matthew 22:23-33' WHERE id = 'st-marriage-and-the-afterlife';
UPDATE stories SET bible_ref = 'Matthew 22:34-40' WHERE id = 'st-the-greatest-commandment';
UPDATE stories SET bible_ref = 'Matthew 22:41-46' WHERE id = 'st-whose-son-is-the-messiah';
UPDATE stories SET bible_ref = 'Matthew 24-25' WHERE id = 'st-signs-of-the-end';
UPDATE stories SET bible_ref = 'Matthew 26:1-5' WHERE id = 'st-the-plot-against-jesus';
UPDATE stories SET bible_ref = 'Matthew 26:14-16' WHERE id = 'st-judas-makes-a-deal';
UPDATE stories SET bible_ref = 'John 12:1-8' WHERE id = 'st-anointed-at-bethany';
UPDATE stories SET bible_ref = 'Matthew 26:36-46' WHERE id = 'st-gethsemane';
UPDATE stories SET bible_ref = 'Matthew 26:47-56' WHERE id = 'st-arrested-in-the-garden';
UPDATE stories SET bible_ref = 'Matthew 26:57-68' WHERE id = 'st-before-the-sanhedrin';
UPDATE stories SET bible_ref = 'Matthew 26:69-75' WHERE id = 'st-peters-three-denials';
UPDATE stories SET bible_ref = 'Matthew 27:11-26' WHERE id = 'st-jesus-before-pilate';
UPDATE stories SET bible_ref = 'Matthew 27:57-66' WHERE id = 'st-buried-in-a-borrowed-tomb';
UPDATE stories SET bible_ref = 'Luke 24:13-35' WHERE id = 'st-the-road-to-emmaus';
UPDATE stories SET bible_ref = 'John 20:24-29' WHERE id = 'st-doubting-thomas';
UPDATE stories SET bible_ref = 'Matthew 28:16-20' WHERE id = 'st-the-great-commission';
UPDATE stories SET bible_ref = 'Acts 1:1-11' WHERE id = 'st-the-ascension';
UPDATE stories SET bible_ref = 'Acts 2' WHERE id = 'st-pentecost';
UPDATE stories SET bible_ref = 'Acts 3' WHERE id = 'st-the-beautiful-gate-miracle';
UPDATE stories SET bible_ref = 'Acts 5' WHERE id = 'st-ananias-and-sapphira';
UPDATE stories SET bible_ref = 'Acts 6-7' WHERE id = 'st-stephen-the-first-martyr';
UPDATE stories SET bible_ref = 'Acts 8' WHERE id = 'st-the-church-scatters';
UPDATE stories SET bible_ref = 'Acts 9:1-31' WHERE id = 'st-saul-meets-jesus';
UPDATE stories SET bible_ref = 'Acts 9:32-43' WHERE id = 'st-peters-miracles';
UPDATE stories SET bible_ref = 'Acts 10' WHERE id = 'st-cornelius-and-the-vision';
UPDATE stories SET bible_ref = 'Acts 11' WHERE id = 'st-the-antioch-church';
UPDATE stories SET bible_ref = 'Acts 12' WHERE id = 'st-james-killed-peter-escapes';
UPDATE stories SET bible_ref = 'Acts 13-14' WHERE id = 'st-pauls-first-journey';
UPDATE stories SET bible_ref = 'Acts 15' WHERE id = 'st-the-jerusalem-council';
UPDATE stories SET bible_ref = 'Acts 16' WHERE id = 'st-earthquake-at-philippi';
UPDATE stories SET bible_ref = 'Acts 17:1-14' WHERE id = 'st-thessalonica-riot-and-berea';
UPDATE stories SET bible_ref = 'Acts 17:15-34' WHERE id = 'st-athens-the-unknown-god';
UPDATE stories SET bible_ref = 'Acts 19' WHERE id = 'st-riot-in-ephesus';
UPDATE stories SET bible_ref = 'Acts 20:7-12' WHERE id = 'st-eutychus-falls-out-a-window';
UPDATE stories SET bible_ref = 'Acts 20:17-38' WHERE id = 'st-farewell-at-miletus';
UPDATE stories SET bible_ref = 'Acts 21' WHERE id = 'st-arrested-at-the-temple';
UPDATE stories SET bible_ref = 'Acts 24-26' WHERE id = 'st-trials-before-governors';
UPDATE stories SET bible_ref = 'Acts 27-28' WHERE id = 'st-shipwreck-and-malta';
UPDATE stories SET bible_ref = 'Acts 28:16-31' WHERE id = 'st-paul-under-house-arrest';
UPDATE stories SET bible_ref = 'James' WHERE id = 'st-james-writes-to-the-church';
UPDATE stories SET bible_ref = '2 Peter' WHERE id = 'st-peters-final-letter';
UPDATE stories SET bible_ref = '2 Timothy' WHERE id = 'st-pauls-last-letter';
UPDATE stories SET bible_ref = 'Revelation 1' WHERE id = 'st-johns-exile-and-revelation';
UPDATE stories SET bible_ref = 'Revelation 21-22' WHERE id = 'st-the-new-heaven-and-new-earth';
UPDATE stories SET bible_ref = '1 Samuel 1-2' WHERE id = 'st-hannahs-prayer';
UPDATE stories SET bible_ref = '1 Samuel 9-10' WHERE id = 'st-samuel-anoints-saul';
UPDATE stories SET bible_ref = '1 Samuel 13-15' WHERE id = 'st-sauls-downfall';
UPDATE stories SET bible_ref = '1 Samuel 16' WHERE id = 'st-samuel-anoints-david';
UPDATE stories SET bible_ref = '1 Samuel 18-20' WHERE id = 'st-david-and-jonathan';
UPDATE stories SET bible_ref = '1 Samuel 24, 26' WHERE id = 'st-david-spares-saul';
UPDATE stories SET bible_ref = '1 Samuel 28' WHERE id = 'st-the-witch-of-endor';
UPDATE stories SET bible_ref = '1 Kings 5-8' WHERE id = 'st-solomon-builds-the-temple';
UPDATE stories SET bible_ref = '1 Kings 10' WHERE id = 'st-queen-of-sheba';
UPDATE stories SET bible_ref = '1 Kings 11' WHERE id = 'st-solomons-downfall';
UPDATE stories SET bible_ref = '1 Kings 17:1-7' WHERE id = 'st-elijah-fed-by-ravens';
UPDATE stories SET bible_ref = '1 Kings 17:8-24' WHERE id = 'st-elijah-and-the-widow';
UPDATE stories SET bible_ref = '1 Kings 19' WHERE id = 'st-elijah-runs-from-jezebel';
UPDATE stories SET bible_ref = '1 Kings 21' WHERE id = 'st-naboths-vineyard';
UPDATE stories SET bible_ref = '2 Kings 2' WHERE id = 'st-elijah-taken-to-heaven';
UPDATE stories SET bible_ref = 'Daniel 2' WHERE id = 'st-nebuchadnezzars-dream';
UPDATE stories SET bible_ref = 'Daniel 3' WHERE id = 'st-the-fiery-furnace';
UPDATE stories SET bible_ref = 'Daniel 5' WHERE id = 'st-the-writing-on-the-wall';
UPDATE stories SET bible_ref = 'Daniel 7-9' WHERE id = 'st-daniels-visions';
UPDATE stories SET bible_ref = 'Esther 1-2' WHERE id = 'st-esther-becomes-queen';
UPDATE stories SET bible_ref = 'Esther 3-4' WHERE id = 'st-hamans-plot';
UPDATE stories SET bible_ref = 'Esther 5-7' WHERE id = 'st-esthers-banquet';
UPDATE stories SET bible_ref = 'Psalm 23' WHERE id = 'st-david-writes-psalm-23';
UPDATE stories SET bible_ref = 'Psalms 42, 51, 88' WHERE id = 'st-songs-in-the-night';
UPDATE stories SET bible_ref = 'Job 1-2, 38-42' WHERE id = 'st-jobs-suffering';
UPDATE stories SET bible_ref = 'Proverbs 1-9' WHERE id = 'st-solomons-proverbs';
UPDATE stories SET bible_ref = 'Isaiah 6' WHERE id = 'st-isaiahs-vision';
UPDATE stories SET bible_ref = 'Jeremiah 1, 20, 38' WHERE id = 'st-jeremiah-the-weeping-prophet';
UPDATE stories SET bible_ref = 'Ezekiel 37' WHERE id = 'st-valley-of-dry-bones';
UPDATE stories SET bible_ref = 'Hosea 1-3' WHERE id = 'st-hosea-and-gomer';
UPDATE stories SET bible_ref = 'Jonah 3-4' WHERE id = 'st-jonahs-anger';
UPDATE stories SET bible_ref = 'Revelation 2-3' WHERE id = 'st-letters-to-seven-churches';
UPDATE stories SET bible_ref = 'Revelation 6' WHERE id = 'st-the-four-horsemen';
UPDATE stories SET bible_ref = 'Revelation 17-18' WHERE id = 'st-the-fall-of-babylon';
UPDATE stories SET bible_ref = '1 Corinthians 13' WHERE id = 'st-love-is';
UPDATE stories SET bible_ref = 'Ephesians 6:10-20' WHERE id = 'st-armor-of-god';
UPDATE stories SET bible_ref = '1 Timothy 1, 2 Timothy 1' WHERE id = 'st-paul-and-timothy';
UPDATE stories SET bible_ref = 'Romans 1-8' WHERE id = 'st-pauls-letter-to-rome';
UPDATE stories SET bible_ref = 'Ruth 1-4' WHERE id = 'st-ruth-and-boaz';
UPDATE stories SET bible_ref = 'Psalm 51' WHERE id = 'st-psalm-51-a-broken-king';
UPDATE stories SET bible_ref = 'Psalm 91' WHERE id = 'st-psalm-91-gods-protection';
UPDATE stories SET bible_ref = 'Psalm 139' WHERE id = 'st-psalm-139-fully-known';
UPDATE stories SET bible_ref = 'Psalm 150' WHERE id = 'st-psalm-150-everything-praise';
UPDATE stories SET bible_ref = 'Job 2-31' WHERE id = 'st-jobs-friends-speak';
UPDATE stories SET bible_ref = 'Job 38-41' WHERE id = 'st-god-answers-job';
UPDATE stories SET bible_ref = 'Job 42' WHERE id = 'st-job-restored';
UPDATE stories SET bible_ref = 'Proverbs 1-9' WHERE id = 'st-the-wise-and-the-foolish';
UPDATE stories SET bible_ref = 'Proverbs 31:10-31' WHERE id = 'st-the-proverbs-31-woman';
UPDATE stories SET bible_ref = 'Isaiah 6' WHERE id = 'st-isaiahs-call';
UPDATE stories SET bible_ref = 'Isaiah 7, 9' WHERE id = 'st-immanuel-prophecy';
UPDATE stories SET bible_ref = 'Isaiah 65-66' WHERE id = 'st-new-heavens-new-earth-isaiah';
UPDATE stories SET bible_ref = 'Jeremiah 18-19' WHERE id = 'st-the-potters-clay';
UPDATE stories SET bible_ref = 'Jeremiah 38' WHERE id = 'st-jeremiah-in-the-cistern';
UPDATE stories SET bible_ref = 'Jeremiah 31:31-34' WHERE id = 'st-the-new-covenant';
UPDATE stories SET bible_ref = 'Ezekiel 1-3' WHERE id = 'st-ezekiels-call-and-the-wheel';
UPDATE stories SET bible_ref = 'Ezekiel 47' WHERE id = 'st-the-restored-temple';
UPDATE stories SET bible_ref = 'Hosea 2-3' WHERE id = 'st-israels-unfaithfulness';
UPDATE stories SET bible_ref = 'Hosea 11, 14' WHERE id = 'st-gods-love-wins';
UPDATE stories SET bible_ref = '2 Chronicles 5-7' WHERE id = 'st-solomons-temple-dedication';
UPDATE stories SET bible_ref = '2 Chronicles 29-30' WHERE id = 'st-hezekiahs-revival';
UPDATE stories SET bible_ref = 'James 3' WHERE id = 'st-taming-the-tongue';
UPDATE stories SET bible_ref = 'James 2:14-26' WHERE id = 'st-faith-without-works';
UPDATE stories SET bible_ref = '2 Peter 2-3' WHERE id = 'st-guard-the-truth';
UPDATE stories SET bible_ref = '2 Timothy 4' WHERE id = 'st-finish-the-race';
