import { readFileSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");
const APP_ID = "true-crime-tea";
const CONTENT_DIR = join(ROOT, "apps", APP_ID, "content");
const CATALOG_PATH = join(CONTENT_DIR, "story-catalog.json");
const OUT_PATH = join(__dirname, "db-populate-true-crime.sql");

interface CatalogStory {
  id: string;
  title: string;
  description: string;
  section: string;
  bibleRef: string;
  inSeed: boolean;
  seedId: string | null;
}

const catalog: CatalogStory[] = JSON.parse(readFileSync(CATALOG_PATH, "utf8"));

function esc(s: string): string {
  return s.replace(/'/g, "''");
}

function slugify(s: string): string {
  return s
    .toLowerCase()
    .replace(/&/g, "and")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

function storyDbId(catalogId: string, seedId: string | null): string {
  return seedId ?? `st-${catalogId}`;
}

/** DB testament is still old|new — map case types into two library shelves. */
const CLASSIC_SECTIONS = new Set([
  "Unsolved",
  "Cold Cases",
  "Disappearances",
]);

function testamentFor(section: string): "old" | "new" {
  return CLASSIC_SECTIONS.has(section) ? "old" : "new";
}

const SECTION_DESCRIPTIONS: Record<string, string> = {
  Heists: "Vaults, diamonds, art, and the scores that became legends.",
  Escapes: "Tunnels, helicopters, and the prisoners who refused to stay put.",
  Unsolved: "Open files. Missing answers. The cases that still haunt investigators.",
  "Cold Cases": "Old crimes cracked — or reopened — by obsession and new science.",
  Scandals: "Corruption, cover-ups, and the lies that took down empires.",
  Disappearances: "People and planes that walked out of history.",
  "Con Artists": "Long cons, forged identities, and charm as a weapon.",
};

interface Season {
  id: string;
  name: string;
  slug: string;
  testament: "old" | "new";
  description: string;
  sortOrder: number;
}

const seasonsByName = new Map<string, Season>();
let seasonOrder = 10;
for (const story of catalog) {
  if (seasonsByName.has(story.section)) continue;
  const slug = slugify(story.section);
  seasonsByName.set(story.section, {
    id: `s-tct-${slug}`,
    name: story.section,
    slug: `tct-${slug}`,
    testament: testamentFor(story.section),
    description: SECTION_DESCRIPTIONS[story.section] ?? "",
    sortOrder: seasonOrder,
  });
  seasonOrder += 10;
}

const sql: string[] = [];
sql.push("-- ============================================");
sql.push(`-- Auto-generated by scripts/db-populate-true-crime.ts`);
sql.push(`-- App: ${APP_ID}`);
sql.push(`-- Stories: ${catalog.length}, Seasons: ${seasonsByName.size}`);
sql.push("-- ============================================");
sql.push("");

sql.push("-- ── SEASONS ──");
for (const s of seasonsByName.values()) {
  sql.push(
    `INSERT OR IGNORE INTO seasons (id, app_id, testament, name, slug, description, sort_order) VALUES ('${s.id}', '${APP_ID}', '${s.testament}', '${esc(s.name)}', '${s.slug}', '${esc(s.description)}', ${s.sortOrder});`
  );
}
sql.push("");

sql.push("-- ── STORIES ──");
let storyOrder = 100;
for (const story of catalog) {
  const season = seasonsByName.get(story.section);
  if (!season) continue;
  const dbId = storyDbId(story.id, story.seedId);
  const coverKey = `stories/${story.id}/cover.webp`;
  sql.push(
    `INSERT OR IGNORE INTO stories (id, app_id, season_id, title, slug, description, cover_image_key, sort_order, is_free, is_published) VALUES ('${dbId}', '${APP_ID}', '${season.id}', '${esc(story.title)}', '${esc(story.id)}', '${esc(story.description)}', '${coverKey}', ${storyOrder}, 1, 1);`
  );
  storyOrder += 1;
}
sql.push("");

sql.push("-- ── SPEAKERS ──");
sql.push(
  `INSERT OR IGNORE INTO speakers (id, app_id, name, bio, voice_style, is_default) VALUES ('sp-tct-elijah', '${APP_ID}', 'Elijah', 'Deep, steady narrator.', 'steady', 1);`
);
sql.push(
  `INSERT OR IGNORE INTO speakers (id, app_id, name, bio, voice_style, is_default) VALUES ('sp-tct-grace', '${APP_ID}', 'Grace', 'Warm, conversational narrator.', 'warm', 0);`
);
sql.push("");

sql.push("-- ── STORY AUDIO (placeholders — narrate later) ──");
const SPEAKER_IDS = { elijah: "sp-tct-elijah", grace: "sp-tct-grace" } as const;
let audioCount = 0;
for (const story of catalog) {
  const dbStoryId = storyDbId(story.id, story.seedId);
  for (const [voice, speakerId] of Object.entries(SPEAKER_IDS)) {
    const audioId = `sa-tct-${story.id}-${voice}`;
    const audioKey = `stories/${story.id}/narration-${voice}.mp3`;
    sql.push(
      `INSERT OR IGNORE INTO story_audio (id, story_id, speaker_id, audio_key, duration_seconds) VALUES ('${audioId}', '${dbStoryId}', '${speakerId}', '${audioKey}', 0);`
    );
    audioCount++;
  }
}
sql.push("");

writeFileSync(OUT_PATH, sql.join("\n"), "utf8");
console.log(`Generated ${OUT_PATH}`);
console.log(`  Seasons: ${seasonsByName.size}`);
console.log(`  Stories: ${catalog.length}`);
console.log(`  Speakers: 2`);
console.log(`  Story audio rows: ${audioCount}`);
